/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import Business.Organization.DiseaseManagementOrganization;
import Business.Person.Patient;
import Business.Person.Person;
import Business.SocialForum.Disease;
import Business.SocialForum.Topic;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saurabh Goyal
 */
public class ThreadsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ThreadsJPanel
     */
    private JPanel userProcessContainer;
    private Disease disease;
    private DiseaseManagementOrganization dmo;
    private Patient patient;

    public ThreadsJPanel(JPanel userProcessContainer, DiseaseManagementOrganization dmo, Disease disease, Person person) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.disease = disease;
        lblDName.setText(disease.getDiseaseName());
        this.dmo = dmo;
        this.patient = (Patient)person;
        jplCreateTopic.setVisible(false);
        populateThreadTable();
    }

    private void populateThreadTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblThreads.getModel();
        dtm.setRowCount(0);

        for (Topic t : dmo.getTopicList()) {
            if (t.getDisease() == disease) {
                
                Object[] row = new Object[2];
                row[0] = t;
                row[1] = t.getWorkQueue().getWorkRequestList().size();

                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblListOfThreads = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblThreads = new javax.swing.JTable();
        lblDisease = new javax.swing.JLabel();
        lblDName = new javax.swing.JLabel();
        btnCreateTopic = new javax.swing.JCheckBox();
        jplCreateTopic = new javax.swing.JPanel();
        lblTopicName = new javax.swing.JLabel();
        txtTopicName = new javax.swing.JTextField();
        btnCreateTopic1 = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnViewDiscussion = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblListOfThreads.setText("List of Threads");

        tblThreads.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Topic Name", "Number of Posts"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblThreads);
        if (tblThreads.getColumnModel().getColumnCount() > 0) {
            tblThreads.getColumnModel().getColumn(0).setResizable(false);
            tblThreads.getColumnModel().getColumn(1).setResizable(false);
        }

        lblDisease.setText("Disease");

        btnCreateTopic.setText("Create Topic");
        btnCreateTopic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateTopicActionPerformed(evt);
            }
        });

        lblTopicName.setText("Topic Name");

        btnCreateTopic1.setText("Create Topic");
        btnCreateTopic1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateTopic1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jplCreateTopicLayout = new javax.swing.GroupLayout(jplCreateTopic);
        jplCreateTopic.setLayout(jplCreateTopicLayout);
        jplCreateTopicLayout.setHorizontalGroup(
            jplCreateTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplCreateTopicLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTopicName)
                .addGap(18, 18, 18)
                .addComponent(txtTopicName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnCreateTopic1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jplCreateTopicLayout.setVerticalGroup(
            jplCreateTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplCreateTopicLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplCreateTopicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTopicName)
                    .addComponent(txtTopicName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreateTopic1))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnViewDiscussion.setText("View Discussion>>");
        btnViewDiscussion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDiscussionActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateTopic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jplCreateTopic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDisease)
                        .addGap(40, 40, 40)
                        .addComponent(lblDName))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblListOfThreads, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRefresh)))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewDiscussion)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDisease)
                    .addComponent(lblDName))
                .addGap(31, 31, 31)
                .addComponent(lblListOfThreads)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreateTopic)
                            .addComponent(jplCreateTopic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(btnViewDiscussion)
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack)
                        .addGap(25, 25, 25))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateTopicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTopicActionPerformed
        // TODO add your handling code here:
        if(btnCreateTopic.isSelected()){
            jplCreateTopic.setVisible(true);
        }
        
        if(!btnCreateTopic.isSelected()){
            jplCreateTopic.setVisible(false);
        }
    }//GEN-LAST:event_btnCreateTopicActionPerformed

    private void btnCreateTopic1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateTopic1ActionPerformed
        // TODO add your handling code here:
        String topicName = txtTopicName.getText();
        if(topicName.isEmpty()){
            JOptionPane.showMessageDialog(null,"Please enter a topic name first.");
            return;
        }
        
        for(Topic t : dmo.getTopicList()){
            if(t.getTopicName() == topicName && t.getDisease()==disease){
                JOptionPane.showMessageDialog(null,"This topic name already exist for this disease.");
                return;
            }
        }
        
        Topic topic = new Topic();
        topic.setDisease(disease);
        topic.setThreadName(topicName);
        dmo.getTopicList().add(topic);
        
    }//GEN-LAST:event_btnCreateTopic1ActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateThreadTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnViewDiscussionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDiscussionActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblThreads.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a thread first.");
            return;
        }
        Topic topic = (Topic)tblThreads.getValueAt(selectedRow, 0);
        
        ViewDiscussionJPanel vdjp = new ViewDiscussionJPanel(userProcessContainer, topic, patient);
        userProcessContainer.add("View Discussion",vdjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewDiscussionActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JCheckBox btnCreateTopic;
    private javax.swing.JButton btnCreateTopic1;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnViewDiscussion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jplCreateTopic;
    private javax.swing.JLabel lblDName;
    private javax.swing.JLabel lblDisease;
    private javax.swing.JLabel lblListOfThreads;
    private javax.swing.JLabel lblTopicName;
    private javax.swing.JTable tblThreads;
    private javax.swing.JTextField txtTopicName;
    // End of variables declaration//GEN-END:variables
}
