/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import Business.Person.Patient;
import Business.Person.Person;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saurabh Goyal
 */
public class ViewLabTestRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewLabTestRequestJPanel
     */
    private JPanel userProcessContainer;
    private Patient patient;

    public ViewLabTestRequestJPanel(JPanel userProcesContainer, Patient patient) {
        initComponents();
        this.userProcessContainer = userProcesContainer;
        this.patient = patient;
        populateWorkRequestTable();
    }

    private void populateWorkRequestTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblLabTestWorkRequest.getModel();
        dtm.setRowCount(0);

        for (WorkRequest wr : patient.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof LabTestWorkRequest) {
                LabTestWorkRequest ltwr = (LabTestWorkRequest) wr;

                Object[] row = new Object[7];
                row[0] = ltwr;
                row[1] = ltwr.getRequestDate();
                row[2] = ltwr.getEnterprise().getOrgName();
                row[3] = ltwr.getSender().getFirstName() + " " + ltwr.getSender().getLastName();
                if (ltwr.getReceiver() != null) {
                    row[4] = ltwr.getReceiver().getFirstName() + " " + ltwr.getReceiver().getLastName();
                }
                row[5] = ltwr.getStatus();
                row[6] = ltwr.getLabTestResult();
                
                dtm.addRow(row);
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLabTestWorkRequest = new javax.swing.JTable();

        jLabel1.setText("Lab Test Requests");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblLabTestWorkRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Date", "Enterprise Name", "Sender Doctor", "Receiver ", "Status", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLabTestWorkRequest);
        if (tblLabTestWorkRequest.getColumnModel().getColumnCount() > 0) {
            tblLabTestWorkRequest.getColumnModel().getColumn(0).setResizable(false);
            tblLabTestWorkRequest.getColumnModel().getColumn(1).setResizable(false);
            tblLabTestWorkRequest.getColumnModel().getColumn(2).setResizable(false);
            tblLabTestWorkRequest.getColumnModel().getColumn(3).setResizable(false);
            tblLabTestWorkRequest.getColumnModel().getColumn(4).setResizable(false);
            tblLabTestWorkRequest.getColumnModel().getColumn(5).setResizable(false);
            tblLabTestWorkRequest.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(89, 89, 89)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLabTestWorkRequest;
    // End of variables declaration//GEN-END:variables
}
