/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminRole.ManageEnterpriseAdmin;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.CityNetwork;
import Business.Network.CountryNetwork;
import Business.Network.StateNetwork;
import Business.Role.AdminRole;
import Business.Role.MainAuthorityAdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saurabh Goyal
 */
public class ManageEnterpriseAdminUserAccount extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseAdminUserAccount
     */
    private JPanel userProcessContainer;
    private EcoSystem system;

    public ManageEnterpriseAdminUserAccount(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateAdminUserAccountTable();
    }

    private void populateAdminUserAccountTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblAdminUserAccounts.getModel();
        dtm.setRowCount(0);

        if(system.getMainAuthorityEnterprise()!=null){
            for(UserAccount ua : system.getMainAuthorityEnterprise().getUserAccountDirectory().getUserAccountList()){
                if(ua.getRole() instanceof MainAuthorityAdminRole){
                    Object[] row = new Object[6];
                                
                                row[0] = system.getMainAuthorityEnterprise();
                                row[1] = system.getMainAuthorityEnterprise().getEnterpriseType();
                                row[2] = ua;
                                                               
                                dtm.addRow(row);
                }
            }
        }
        for (CountryNetwork cn : system.getCountryNetworkList()) {
            for (StateNetwork sn : cn.getStateNetwork()) {
                for (CityNetwork cin : sn.getCityNetwork()) {
                    for (Enterprise e : cin.getEnterpriseDirectory().getEnterpriseList()) {
                        for (UserAccount ua : e.getUserAccountDirectory().getUserAccountList()) {
                            if (ua.getRole() instanceof AdminRole) {
                                
                                Object[] row = new Object[6];
                                
                                row[0] = e;
                                row[1] = e.getEnterpriseType();
                                row[2] = ua;
                                row[3] = cn;
                                row[4] = sn;
                                row[5] = cin;
                                
                                dtm.addRow(row);
                            }
                        }
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManageEnterpriseAdmin = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdminUserAccounts = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnAddEnterpriseAdmin = new javax.swing.JButton();
        btnDeleteEnterpriseAdmin = new javax.swing.JButton();

        lblManageEnterpriseAdmin.setText("Manage Enterprise Admin User Account");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblAdminUserAccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Enterprise Name", "Enterprise Type", "Username", "Country", "State", "City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAdminUserAccounts);
        if (tblAdminUserAccounts.getColumnModel().getColumnCount() > 0) {
            tblAdminUserAccounts.getColumnModel().getColumn(0).setResizable(false);
            tblAdminUserAccounts.getColumnModel().getColumn(1).setResizable(false);
            tblAdminUserAccounts.getColumnModel().getColumn(2).setResizable(false);
            tblAdminUserAccounts.getColumnModel().getColumn(3).setResizable(false);
            tblAdminUserAccounts.getColumnModel().getColumn(4).setResizable(false);
            tblAdminUserAccounts.getColumnModel().getColumn(5).setResizable(false);
        }

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnAddEnterpriseAdmin.setText("Add Enterprise Admin");
        btnAddEnterpriseAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEnterpriseAdminActionPerformed(evt);
            }
        });

        btnDeleteEnterpriseAdmin.setText("Delete Enterprise Admin");
        btnDeleteEnterpriseAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEnterpriseAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(btnDeleteEnterpriseAdmin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAddEnterpriseAdmin))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(192, 192, 192)
                            .addComponent(lblManageEnterpriseAdmin))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(494, 494, 494)
                            .addComponent(btnRefresh))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(btnBack))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblManageEnterpriseAdmin)
                .addGap(26, 26, 26)
                .addComponent(btnRefresh)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddEnterpriseAdmin)
                    .addComponent(btnDeleteEnterpriseAdmin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(32, 32, 32))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddEnterpriseAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEnterpriseAdminActionPerformed
        // TODO add your handling code here:
        AddEnterpriseAdminJPanel aeajp = new AddEnterpriseAdminJPanel(userProcessContainer, system);
        userProcessContainer.add("Add enterprise admin", aeajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddEnterpriseAdminActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateAdminUserAccountTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDeleteEnterpriseAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEnterpriseAdminActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblAdminUserAccounts.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select an admin first.");
            return;
        }
        
        Enterprise e = (Enterprise)tblAdminUserAccounts.getValueAt(selectedRow, 0);
        UserAccount ua = (UserAccount)tblAdminUserAccounts.getValueAt(selectedRow,2);
        
        int d = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete.", "Warning", JOptionPane.YES_NO_OPTION);
        if(d==JOptionPane.YES_OPTION){
            e.getPersonDirectory().getPerosonList().remove(ua.getPerson());
            e.getUserAccountDirectory().getUserAccountList().remove(ua);
        }
    }//GEN-LAST:event_btnDeleteEnterpriseAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEnterpriseAdmin;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteEnterpriseAdmin;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblManageEnterpriseAdmin;
    private javax.swing.JTable tblAdminUserAccounts;
    // End of variables declaration//GEN-END:variables
}
