/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.DrugRegulatoryEmployeeRole;

import Business.PharmaceuticalCompany.DrugGuideline;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Saurabh Goyal
 */
public class ViewMedicationGuidelineJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewMedicationGuidelineJPanel
     */
    private JPanel userProcessContainer;
    private DrugGuideline guideline;
    public ViewMedicationGuidelineJPanel(JPanel userProcesscontainer, DrugGuideline guideline) {
        initComponents();
        this.userProcessContainer = userProcesscontainer;
        this.guideline = guideline;
        populateFields();
    }
    
    private void populateFields(){
        txtDrugInfo.setText(guideline.getDrugInfo());
        txtDrugNoUse.setText(guideline.getDrugNoUse());
        txtDrugUse.setText(guideline.getDrugUse());
        txtDurgDoctorInfo.setText(guideline.getDrugDoctorInfo());
        txtHowToUse.setText(guideline.getHowToUse());
        txtIngridients.setText(guideline.getIngridients());
        txtRefillInfo.setText(guideline.getRefillInfo());
        txtSideEffect.setText(guideline.getSideEffect());
        txtStoreInfo.setText(guideline.getStoreInfo());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDrugGuideline = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDrugInfo = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDurgDoctorInfo = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDrugNoUse = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDrugUse = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtHowToUse = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtSideEffect = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        txtStoreInfo = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtIngridients = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtRefillInfo = new javax.swing.JTextArea();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDrugGuideline.setText("Drug Guideline");
        add(lblDrugGuideline, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 0, -1, -1));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 529, -1, -1));

        jLabel1.setText("Important information about drug that patient should know. ");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 39, -1, -1));

        txtDrugInfo.setEditable(false);
        txtDrugInfo.setColumns(20);
        txtDrugInfo.setRows(5);
        jScrollPane1.setViewportView(txtDrugInfo);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 64, 290, 53));

        jLabel2.setText("Info for healthcare provider before using the drug.");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 330, -1, -1));

        txtDurgDoctorInfo.setEditable(false);
        txtDurgDoctorInfo.setColumns(20);
        txtDurgDoctorInfo.setRows(5);
        jScrollPane2.setViewportView(txtDurgDoctorInfo);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 355, 290, 51));

        jLabel3.setText("Who should not use this drug.");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 242, -1, -1));

        txtDrugNoUse.setEditable(false);
        txtDrugNoUse.setColumns(20);
        txtDrugNoUse.setRows(5);
        jScrollPane3.setViewportView(txtDrugNoUse);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 267, 290, 53));

        jLabel4.setText("Whis is this drug?");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 145, -1, -1));

        txtDrugUse.setEditable(false);
        txtDrugUse.setColumns(20);
        txtDrugUse.setRows(5);
        jScrollPane4.setViewportView(txtDrugUse);

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 171, 290, 48));

        jLabel5.setText("How to use the drug?");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 424, -1, -1));

        txtHowToUse.setEditable(false);
        txtHowToUse.setColumns(20);
        txtHowToUse.setRows(5);
        jScrollPane5.setViewportView(txtHowToUse);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 449, 290, 50));

        jLabel6.setText("Info of the possible side effects of the drug");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 39, -1, -1));

        txtSideEffect.setEditable(false);
        txtSideEffect.setColumns(20);
        txtSideEffect.setRows(5);
        jScrollPane6.setViewportView(txtSideEffect);

        add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 64, 260, 53));

        jLabel7.setText("Info about storing the drug.");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 145, -1, -1));

        txtStoreInfo.setEditable(false);
        txtStoreInfo.setColumns(20);
        txtStoreInfo.setRows(5);
        jScrollPane7.setViewportView(txtStoreInfo);

        add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 176, 260, 48));

        jLabel8.setText("Ingridients of the drug.");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 242, -1, -1));

        txtIngridients.setEditable(false);
        txtIngridients.setColumns(20);
        txtIngridients.setRows(5);
        jScrollPane8.setViewportView(txtIngridients);

        add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 267, 260, 50));

        jLabel9.setText("When to get refill for the drug?");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 339, -1, -1));

        txtRefillInfo.setEditable(false);
        txtRefillInfo.setColumns(20);
        txtRefillInfo.setRows(5);
        jScrollPane9.setViewportView(txtRefillInfo);

        add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 359, 260, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JLabel lblDrugGuideline;
    private javax.swing.JTextArea txtDrugInfo;
    private javax.swing.JTextArea txtDrugNoUse;
    private javax.swing.JTextArea txtDrugUse;
    private javax.swing.JTextArea txtDurgDoctorInfo;
    private javax.swing.JTextArea txtHowToUse;
    private javax.swing.JTextArea txtIngridients;
    private javax.swing.JTextArea txtRefillInfo;
    private javax.swing.JTextArea txtSideEffect;
    private javax.swing.JTextArea txtStoreInfo;
    // End of variables declaration//GEN-END:variables
}
