/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminRole;

import UserInterface.AdminRole.PharmaceuticalCompany.AddDrugManagementEmployeeJPanel;
import UserInterface.AdminRole.PharmaceuticalCompany.AddResearchEmployeeJPanel;
import Business.Enterprise.Enterprise;
import Business.Enterprise.MainAuthorityEnterprise;
import Business.Organization.DiseaseManagementOrganization;
import Business.Organization.DoctorOrganization;
import Business.Organization.DrugManagementOrganization;
import Business.Organization.DrugRegulatoryOrganization;
import Business.Organization.LabOrganization;
import Business.Organization.NurseOrganization;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.Organization.ResearchOrganization;
import Business.Person.PersonDirectory;
import UserInterface.MainAuthorityAdminRole.AddDiseaseManagementEmployeeJPanel;
import UserInterface.MainAuthorityAdminRole.AddDrugRegulatoryEmployeeJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Saurabh Goyal
 */
public class AddEmployeeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddEmployeeJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private PersonDirectory mainDoctorPersonDirectory;

    public AddEmployeeJPanel(JPanel userProcessContainer, Enterprise enterprise, PersonDirectory mainDoctorPersonDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.mainDoctorPersonDirectory = mainDoctorPersonDirectory;
        populateOrganizationComboBox();
    }

    private void populateOrganizationComboBox() {

        cmbOrganization.removeAllItems();

        if (enterprise instanceof MainAuthorityEnterprise) {
            for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (!((o instanceof PatientOrganization) || (o instanceof DoctorOrganization))) {
                    cmbOrganization.addItem(o);
                }
            }
        }
        else{
            for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (!(o instanceof PatientOrganization)) {
                cmbOrganization.addItem(o);
            }
        }
        }
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbOrganization = new javax.swing.JComboBox();
        lblOrganization = new javax.swing.JLabel();
        lblSelect = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jLabel1.setText("Add Employee");

        cmbOrganization.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrganizationActionPerformed(evt);
            }
        });

        lblOrganization.setText("Organization");

        lblSelect.setText("Select an organization");

        btnNext.setText("Next>>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOrganization)
                            .addComponent(lblSelect))
                        .addGap(53, 53, 53)
                        .addComponent(cmbOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addComponent(lblSelect)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOrganization))
                .addGap(39, 39, 39)
                .addComponent(btnNext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrganizationActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbOrganizationActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        Organization o = (Organization) cmbOrganization.getSelectedItem();

        if (o != null) {
            if (o instanceof DoctorOrganization) {
                AddDoctorJPanel adjp = new AddDoctorJPanel(userProcessContainer, o,enterprise, mainDoctorPersonDirectory);
                userProcessContainer.add("Add Doctor", adjp);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }

            if (o instanceof NurseOrganization) {

                AddNurseJPanel anjp = new AddNurseJPanel(userProcessContainer, o);
                userProcessContainer.add("Add Nurse", anjp);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }

            if (o instanceof LabOrganization) {
                AddLabAssistantJPanel alajp = new AddLabAssistantJPanel(userProcessContainer, o);
                userProcessContainer.add("Add Lab Assistant", alajp);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }

            if (o instanceof DrugManagementOrganization) {
                AddDrugManagementEmployeeJPanel admejp = new AddDrugManagementEmployeeJPanel(userProcessContainer, o);
                userProcessContainer.add("Add Drug Management Employee", admejp);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }

            if (o instanceof ResearchOrganization) {
                AddResearchEmployeeJPanel arejp = new AddResearchEmployeeJPanel(userProcessContainer, o);
                userProcessContainer.add("Add Research Employee", arejp);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            
            if(o instanceof DrugRegulatoryOrganization){
                AddDrugRegulatoryEmployeeJPanel adrejp = new AddDrugRegulatoryEmployeeJPanel(userProcessContainer, o);
                userProcessContainer.add("Add Dru Regulatory Employee", adrejp);
                CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }
            
            if(o instanceof DiseaseManagementOrganization){
                AddDiseaseManagementEmployeeJPanel admejp = new AddDiseaseManagementEmployeeJPanel(userProcessContainer, o);
                userProcessContainer.add("Add Disease Management Employee",admejp);
                CardLayout layout = (CardLayout)userProcessContainer.getLayout();
                layout.next(userProcessContainer);
            }

        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JComboBox cmbOrganization;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblSelect;
    // End of variables declaration//GEN-END:variables
}
