/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.NurseRole;

import Business.Organization.Organization;
import Business.Person.Nurse;
import Business.Person.Person;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.NurseWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saurabh Goyal
 */
public class NurseWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NurseWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Organization nurseOrganization;
    private Nurse nurse;
    private WorkRequest request;
    public NurseWorkAreaJPanel(JPanel userProcessContainer, Organization nurseOrganization, Person person) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.nurseOrganization = nurseOrganization;
        this.nurse = (Nurse) person;
        lblResult.setVisible(false);
        txtResult.setVisible(false);
        btnUpdateResult.setVisible(false);
        populateWorkRequestTable();
    }
    
    private void populateWorkRequestTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblLabTestWorkRequest.getModel();
        dtm.setRowCount(0);

        for (WorkRequest wr : nurseOrganization.getWorkQueue().getWorkRequestList()) {

            if (wr instanceof NurseWorkRequest) {
                NurseWorkRequest nwr = (NurseWorkRequest) wr;

                Object[] row = new Object[6];
                row[0] = nwr;
                row[1] = nwr.getRequestDate();
                row[2] = nwr.getSender().getFirstName() + " " + nwr.getSender().getLastName();
                if (nwr.getReceiver() != null) {
                    row[3] = nwr.getReceiver().getFirstName() + " " + nwr.getReceiver().getLastName();
                }
                row[4] = nwr.getStatus();
                row[5] = nwr.getResult();

                dtm.addRow(row);

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnUpdateResult = new javax.swing.JButton();
        txtResult = new javax.swing.JTextField();
        lblResult = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        btnProcessRequest = new javax.swing.JButton();
        btnAssignToMe = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLabTestWorkRequest = new javax.swing.JTable();

        jLabel1.setText("Nurse Work Area");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnUpdateResult.setText("Update Result");
        btnUpdateResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateResultActionPerformed(evt);
            }
        });

        lblResult.setText("Result");

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnProcessRequest.setText("Process Request");
        btnProcessRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessRequestActionPerformed(evt);
            }
        });

        btnAssignToMe.setText("Assign to Me");
        btnAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToMeActionPerformed(evt);
            }
        });

        tblLabTestWorkRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Date", "Sender Doctor", "Receiver ", "Status", "Result"
            }
        ));
        jScrollPane1.setViewportView(tblLabTestWorkRequest);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(551, 551, 551)
                                .addComponent(btnRefresh))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(287, 287, 287)
                                .addComponent(btnAssignToMe)
                                .addGap(112, 112, 112)
                                .addComponent(btnProcessRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(lblResult)
                                .addGap(47, 47, 47)
                                .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(btnUpdateResult))
                            .addComponent(btnBack)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssignToMe)
                    .addComponent(btnProcessRequest))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResult)
                    .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateResult))
                .addGap(67, 67, 67)
                .addComponent(btnBack)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateResultActionPerformed
        // TODO add your handling code here:
        String result = txtResult.getText();
        if(result.isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter the result  of the requested test.");
            return;
        }
        NurseWorkRequest nwr = (NurseWorkRequest)request;
        if("Processed and result updated".equals(nwr.getStatus())){
            JOptionPane.showMessageDialog(null, "This requesy has already been processed.");
            return;
        }
        nwr.setResult(result);
        nwr.setStatus("Processed and result updated");
        populateWorkRequestTable();
        lblResult.setVisible(false);
        txtResult.setVisible(false);
        btnUpdateResult.setVisible(false);
    }//GEN-LAST:event_btnUpdateResultActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateWorkRequestTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnProcessRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessRequestActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblLabTestWorkRequest.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a work request first.");
            return;
        }
        request = (WorkRequest) tblLabTestWorkRequest.getValueAt(selectedRow, 0);

        if(request.getReceiver()==null){
            JOptionPane.showMessageDialog(null, "Assign this work request to yourself first.");
            return;
        }
        if(request.getReceiver()!=nurse){
            JOptionPane.showMessageDialog(null, "This request is not assigned to you.");
            return;
        }
        lblResult.setVisible(true);
        txtResult.setVisible(true);
        btnUpdateResult.setVisible(true);

    }//GEN-LAST:event_btnProcessRequestActionPerformed

    private void btnAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToMeActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblLabTestWorkRequest.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a work request first.");
            return;
        }
        WorkRequest wr = (WorkRequest) tblLabTestWorkRequest.getValueAt(selectedRow, 0);

        if (wr.getReceiver() != null) {
            JOptionPane.showMessageDialog(null, "This request has already been assigned.");
            return;
        }
        wr.setReceiver(nurse);
        wr.setStatus("Received and processing");
        populateWorkRequestTable();
    }//GEN-LAST:event_btnAssignToMeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignToMe;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnProcessRequest;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnUpdateResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblResult;
    private javax.swing.JTable tblLabTestWorkRequest;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
