/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdminRole.ManageNetwork;

import Business.EcoSystem;
import Business.Network.CountryNetwork;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saurabh Goyal
 */
public class ManageCountryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCountryJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;

    public ManageCountryJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        if (system.getCountryNetworkList().size() > 0) {
            populateCountryTable();
        }
    }

    private void populateCountryTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblCountry.getModel();
        dtm.setRowCount(0);

        for (CountryNetwork cn : system.getCountryNetworkList()) {
            Object[] row = new Object[1];

            row[0] = cn;

            dtm.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManageCountry = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCountry = new javax.swing.JTable();
        txtCountryName = new javax.swing.JTextField();
        lblCountryName = new javax.swing.JLabel();
        btnAddCountry = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnRemoveCountry = new javax.swing.JButton();

        lblManageCountry.setText("Manage Country");

        tblCountry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Country"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCountry);
        if (tblCountry.getColumnModel().getColumnCount() > 0) {
            tblCountry.getColumnModel().getColumn(0).setResizable(false);
        }

        lblCountryName.setText("Country Name");

        btnAddCountry.setText("Add Country");
        btnAddCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCountryActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnRemoveCountry.setText("Remove Country");
        btnRemoveCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveCountryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRefresh)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(176, 176, 176)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(84, 84, 84)
                                        .addComponent(btnAddCountry))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCountryName)
                                        .addGap(58, 58, 58)
                                        .addComponent(txtCountryName, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblManageCountry)
                                    .addGap(104, 104, 104))))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnBack))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(118, 118, 118)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnRemoveCountry))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblManageCountry)
                .addGap(37, 37, 37)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnRemoveCountry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCountryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCountryName))
                .addGap(47, 47, 47)
                .addComponent(btnAddCountry)
                .addGap(36, 36, 36)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCountryActionPerformed
        // TODO add your handling code here:
        
        String coName = txtCountryName.getText();
        Pattern pattern = Pattern.compile("[a-zA-Z ]+");
        Matcher countryName = pattern.matcher(coName);
        
        if(!countryName.matches()){
            JOptionPane.showMessageDialog(null, "Invalid country name.");
            return;
        }
        if (coName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter the country you want to add.");
            return;
        }

        for (CountryNetwork cn : system.getCountryNetworkList()) {
            if (cn.getCountryName().equals(coName)) {
                JOptionPane.showMessageDialog(null, "This country name already exists.");
                return;
            }
        }
        CountryNetwork cn = system.createCountryNetwork();
        cn.setCountryName(coName);
        populateCountryTable();
    }//GEN-LAST:event_btnAddCountryActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateCountryTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnRemoveCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveCountryActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCountry.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a country first.");
            return;
        }

        CountryNetwork cn = (CountryNetwork) tblCountry.getValueAt(selectedRow, 0);
        int c = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this city.", "Warning", JOptionPane.YES_NO_OPTION);
        if (c == JOptionPane.YES_OPTION) {
            system.getCountryNetworkList().remove(cn);
            populateCountryTable();
        }
    }//GEN-LAST:event_btnRemoveCountryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCountry;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRemoveCountry;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCountryName;
    private javax.swing.JLabel lblManageCountry;
    private javax.swing.JTable tblCountry;
    private javax.swing.JTextField txtCountryName;
    // End of variables declaration//GEN-END:variables
}
