/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.SystemAdminRole.ManageNetwork;

import Business.EcoSystem;
import Business.Network.CountryNetwork;
import Business.Network.StateNetwork;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saurabh Goyal
 */
public class ManageStateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageState
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private CountryNetwork cn;
    public ManageStateJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        populateComboBox();
    }
    
    private void populateComboBox(){
        cmbCountry.removeAllItems();
        cmbCountry1.removeAllItems();
        
        for(CountryNetwork cn : system.getCountryNetworkList()){
            cmbCountry.addItem(cn);
            cmbCountry1.addItem(cn);
        }
    }
    
    private void populateStateTable(CountryNetwork cn){
        DefaultTableModel dtm = (DefaultTableModel)tblState.getModel();
        dtm.setRowCount(0);
        
        for(StateNetwork sn : cn.getStateNetwork()){
            Object[] row = new Object[1];
            
            row[0] = sn;
            
            dtm.addRow(row);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManageState = new javax.swing.JLabel();
        cmbCountry = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblState = new javax.swing.JTable();
        lblCountry = new javax.swing.JLabel();
        cmbCountry1 = new javax.swing.JComboBox();
        lblState = new javax.swing.JLabel();
        btnAddState = new javax.swing.JButton();
        txtStateName = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnRemoveState = new javax.swing.JButton();
        lblCountry1 = new javax.swing.JLabel();
        lblState1 = new javax.swing.JLabel();

        lblManageState.setText("Manage State");

        cmbCountry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCountryActionPerformed(evt);
            }
        });

        tblState.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "State"
            }
        ));
        jScrollPane1.setViewportView(tblState);

        lblCountry.setText("Country");

        cmbCountry1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblState.setText("State");

        btnAddState.setText("Add State");
        btnAddState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStateActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRemoveState.setText("Remove State");
        btnRemoveState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveStateActionPerformed(evt);
            }
        });

        lblCountry1.setText("Country");

        lblState1.setText("State");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(lblManageState))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(128, 128, 128)
                        .addComponent(btnAddState))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCountry)
                            .addComponent(lblState))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbCountry1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtStateName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRemoveState)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblState1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCountry1)
                                    .addGap(30, 30, 30)
                                    .addComponent(cmbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblManageState)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCountry1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(lblState1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnRemoveState)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCountry)
                    .addComponent(cmbCountry1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblState)
                    .addComponent(txtStateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(btnAddState)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCountryActionPerformed
        // TODO add your handling code here:
        cn = (CountryNetwork) cmbCountry.getSelectedItem();
        
        if(cn!=null){
            populateStateTable(cn);
        }
    }//GEN-LAST:event_cmbCountryActionPerformed

    private void btnAddStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStateActionPerformed
        // TODO add your handling code here:
        String stateName = txtStateName.getText();
        
        Pattern pattern = Pattern.compile("[a-zA-Z ]+");
        Matcher statName = pattern.matcher(stateName);
        
        if(!statName.matches()){
            JOptionPane.showMessageDialog(null, "Invalid state name.");
            return;
        }
        CountryNetwork cn = (CountryNetwork)cmbCountry1.getSelectedItem();
        if(cn == null){
            JOptionPane.showMessageDialog(null,"No country is selected");
            return;
        }
        if(stateName.isEmpty()){
            JOptionPane.showMessageDialog(null,"Enter a state name.");
            return;
        }
        
        for (StateNetwork sn : cn .getStateNetwork()){
            if(sn.getStateName().equals(stateName)){
                JOptionPane.showMessageDialog(null, "This state name already exists.");
                return;
            }
        }
        StateNetwork sn = new StateNetwork();
        sn.setStateName(stateName);
        cn.addState(sn);
        
    }//GEN-LAST:event_btnAddStateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRemoveStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveStateActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblState.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a State first.");
            return;
        }

        StateNetwork sn = (StateNetwork) tblState.getValueAt(selectedRow, 0);
        int c = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this state.", "Warning", JOptionPane.YES_NO_OPTION);
        if (c == JOptionPane.YES_OPTION) {
            cn.getStateNetwork().remove(sn);
            populateStateTable(cn);
        }
    }//GEN-LAST:event_btnRemoveStateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddState;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRemoveState;
    private javax.swing.JComboBox cmbCountry;
    private javax.swing.JComboBox cmbCountry1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblCountry1;
    private javax.swing.JLabel lblManageState;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblState1;
    private javax.swing.JTable tblState;
    private javax.swing.JTextField txtStateName;
    // End of variables declaration//GEN-END:variables
}
