/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.ClinicEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.PharmaceuticalCompanyEnterprise;
import Business.Network.CityNetwork;
import Business.Network.CountryNetwork;
import Business.Network.StateNetwork;
import Business.Person.Doctor;
import Business.Person.Person;
import Business.WorkQueue.CreateEmergencyWorkRequest;
import Business.WorkQueue.EmergencyEnquiryWorkRequest;
import Business.WorkQueue.WorkRequest;
import UserInterface.ViewBroadCastMessageJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saurabh Goyal
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Person person;
    private EcoSystem system;
    public DoctorWorkAreaJPanel(JPanel userProcessContainer,EcoSystem system, Person person) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.person = person;
        this.system = system;
        populateEmergencyRequestTable();
    }
    
    private void populateEmergencyRequestTable(){
        DefaultTableModel dtm = (DefaultTableModel)tblEmergencyRequest.getModel();
        dtm.setRowCount(0);
        
        for(WorkRequest wr : person.getWorkQueue().getWorkRequestList()){
            if(wr instanceof CreateEmergencyWorkRequest){
                CreateEmergencyWorkRequest cewr = (CreateEmergencyWorkRequest)wr;
                
                Object[] row = new Object[4];
                
                row[0] = cewr;
                row[1] = cewr.getMedicalRecordNumber();
                row[2] = cewr.getPatientName();
                row[3] = cewr.getSenderEnterprise();
                
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDoctorWorkArea = new javax.swing.JLabel();
        btnManagePatientWorkRequest = new javax.swing.JButton();
        viewLabRequest = new javax.swing.JButton();
        btnViewPharmacyRequest = new javax.swing.JButton();
        btnViewSentReferredRequest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmergencyRequest = new javax.swing.JTable();
        btnIssueEnquiry = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        btnManageEmergencyPatients = new javax.swing.JButton();
        btnViewBroadCastMessage = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnViewNurseRequestJPanel = new javax.swing.JButton();

        lblDoctorWorkArea.setText("Doctor Work Area");

        btnManagePatientWorkRequest.setText("Manage Patient Work Request");
        btnManagePatientWorkRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePatientWorkRequestActionPerformed(evt);
            }
        });

        viewLabRequest.setText("View Lab Request");
        viewLabRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLabRequestActionPerformed(evt);
            }
        });

        btnViewPharmacyRequest.setText("View Pharmacy Request");
        btnViewPharmacyRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPharmacyRequestActionPerformed(evt);
            }
        });

        btnViewSentReferredRequest.setText("View Sent Referred Request");
        btnViewSentReferredRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewSentReferredRequestActionPerformed(evt);
            }
        });

        tblEmergencyRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Patient MRN", "Patient Name", "Enterprise Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEmergencyRequest);
        if (tblEmergencyRequest.getColumnModel().getColumnCount() > 0) {
            tblEmergencyRequest.getColumnModel().getColumn(0).setResizable(false);
            tblEmergencyRequest.getColumnModel().getColumn(1).setResizable(false);
            tblEmergencyRequest.getColumnModel().getColumn(2).setResizable(false);
            tblEmergencyRequest.getColumnModel().getColumn(3).setResizable(false);
        }

        btnIssueEnquiry.setText("Issue Enquiry");
        btnIssueEnquiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssueEnquiryActionPerformed(evt);
            }
        });

        lblMessage.setText("Message");

        btnManageEmergencyPatients.setText("Manage Emergency Patients");
        btnManageEmergencyPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEmergencyPatientsActionPerformed(evt);
            }
        });

        btnViewBroadCastMessage.setText("View Broadcast Message");
        btnViewBroadCastMessage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewBroadCastMessageActionPerformed(evt);
            }
        });

        jButton1.setText("View Drug Guidlines");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnViewNurseRequestJPanel.setText("View Nurse Request");
        btnViewNurseRequestJPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewNurseRequestJPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(lblDoctorWorkArea))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMessage)
                                .addGap(18, 18, 18)
                                .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnIssueEnquiry)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnManageEmergencyPatients))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewLabRequest, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(btnViewPharmacyRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViewSentReferredRequest, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(btnViewBroadCastMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManagePatientWorkRequest, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(btnViewNurseRequestJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblDoctorWorkArea)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIssueEnquiry)
                    .addComponent(lblMessage)
                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageEmergencyPatients))
                .addGap(47, 47, 47)
                .addComponent(btnManagePatientWorkRequest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewLabRequest)
                .addGap(9, 9, 9)
                .addComponent(btnViewPharmacyRequest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewSentReferredRequest)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewBroadCastMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(15, 15, 15)
                .addComponent(btnViewNurseRequestJPanel)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManagePatientWorkRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePatientWorkRequestActionPerformed
        // TODO add your handling code here:
        ManagePatientWorkRequestJPanel mpwrjp = new ManagePatientWorkRequestJPanel(userProcessContainer,system, person);
        userProcessContainer.add("Manage Patient Work Request",mpwrjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManagePatientWorkRequestActionPerformed

    private void viewLabRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLabRequestActionPerformed
        // TODO add your handling code here:
        ViewLabRequestJPanel vlrjp = new ViewLabRequestJPanel(userProcessContainer,system, person);
        userProcessContainer.add("View Lab Request",vlrjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_viewLabRequestActionPerformed

    private void btnViewPharmacyRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPharmacyRequestActionPerformed
        // TODO add your handling code here:
        PharmacyRequestJPanel prjp = new PharmacyRequestJPanel(userProcessContainer, person);
        userProcessContainer.add("Pharmacy Request",prjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewPharmacyRequestActionPerformed

    private void btnViewSentReferredRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewSentReferredRequestActionPerformed
        // TODO add your handling code here:
        ViewSentReferredRequestJPanel vsrrjp = new ViewSentReferredRequestJPanel(userProcessContainer, (Doctor)person);
        userProcessContainer.add("View Sent Referred Request",vsrrjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnViewSentReferredRequestActionPerformed

    private void btnIssueEnquiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueEnquiryActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblEmergencyRequest.getSelectedRow();
        
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select an Emergency Request that you want to process.");
            return;
        }
        WorkRequest request = (WorkRequest)tblEmergencyRequest.getValueAt(selectedRow, 0);
        
        Long medicalRecordNumber = (Long)tblEmergencyRequest.getValueAt(selectedRow, 1);
        String message = txtMessage.getText();
        Enterprise enterprise = (Enterprise)tblEmergencyRequest.getValueAt(selectedRow, 3);
        
        EmergencyEnquiryWorkRequest eewr = new EmergencyEnquiryWorkRequest();
        eewr.setMessage(message);
        eewr.setMedicalRecordNumber(medicalRecordNumber);
        eewr.setDoctor((Doctor)person);
        eewr.setEnterprise(enterprise);
        
        for(CountryNetwork cn : system.getCountryNetworkList()){
            for(StateNetwork sn : cn.getStateNetwork()){
                for(CityNetwork cin : sn.getCityNetwork()){
                    for(Enterprise e : cin.getEnterpriseDirectory().getEnterpriseList()){
                        if((e instanceof HospitalEnterprise)||(e instanceof ClinicEnterprise)){
                            e.getWorkQueue().getWorkRequestList().add(eewr);
                        }
                    }
                }
            }
        }
        person.getWorkQueue().getWorkRequestList().add(eewr);
        person.getWorkQueue().getWorkRequestList().remove(request);
        JOptionPane.showMessageDialog(null, "Enquiry issued.");
        populateEmergencyRequestTable();
    }//GEN-LAST:event_btnIssueEnquiryActionPerformed

    private void btnManageEmergencyPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEmergencyPatientsActionPerformed
        // TODO add your handling code here:
        ManageEmergencyPatientsJPanel mepjp = new ManageEmergencyPatientsJPanel(userProcessContainer, person);
        userProcessContainer.add("Manage Emergency Patients",mepjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnManageEmergencyPatientsActionPerformed

    private void btnViewBroadCastMessageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewBroadCastMessageActionPerformed
        // TODO add your handling code here:
        ViewBroadCastMessageJPanel vbcmjp = new ViewBroadCastMessageJPanel(userProcessContainer, person.getWorkQueue());
        userProcessContainer.add("View Broadcast Message0",vbcmjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewBroadCastMessageActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ArrayList<PharmaceuticalCompanyEnterprise> pharmaCompanyList = new ArrayList<>();
        
        for(CountryNetwork cn : system.getCountryNetworkList()){
            for(StateNetwork sn : cn.getStateNetwork()){
                for(CityNetwork cin : sn.getCityNetwork()){
                    for(Enterprise e : cin.getEnterpriseDirectory().getEnterpriseList()){
                        if(e instanceof PharmaceuticalCompanyEnterprise){
                            PharmaceuticalCompanyEnterprise pce = (PharmaceuticalCompanyEnterprise)e;
                            pharmaCompanyList.add(pce);
                        }
                    }
                }
            }
        }
        ViewDrugGuidelinesJPanel vdgjp = new ViewDrugGuidelinesJPanel(userProcessContainer, pharmaCompanyList);
        userProcessContainer.add("View Drug Guidelines",vdgjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnViewNurseRequestJPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewNurseRequestJPanelActionPerformed
        // TODO add your handling code here:
        ViewNurseRequestJPanel vnrjp = new ViewNurseRequestJPanel(userProcessContainer, person);
        userProcessContainer.add("View Nurse Request",vnrjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewNurseRequestJPanelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIssueEnquiry;
    private javax.swing.JButton btnManageEmergencyPatients;
    private javax.swing.JButton btnManagePatientWorkRequest;
    private javax.swing.JButton btnViewBroadCastMessage;
    private javax.swing.JButton btnViewNurseRequestJPanel;
    private javax.swing.JButton btnViewPharmacyRequest;
    private javax.swing.JButton btnViewSentReferredRequest;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDoctorWorkArea;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTable tblEmergencyRequest;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JButton viewLabRequest;
    // End of variables declaration//GEN-END:variables
}
