/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.EcoSystem;
import Business.Encounter.Encounter;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.Network.CityNetwork;
import Business.Network.CountryNetwork;
import Business.Network.StateNetwork;
import Business.PharmaceuticalCompany.Drug;
import Business.PharmaceuticalCompany.DrugItem;
import Business.WorkQueue.PharmacyWorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Saurabh Goyal
 */
public class UpdateMedicineJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateMedicineJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem system;
    private Encounter encounter;

    public UpdateMedicineJPanel(JPanel userProcessContainer, EcoSystem system, Encounter encounter) {
        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.encounter = encounter;
        populateCountryComboBox();
    }

    private void populateCountryComboBox() {

        cmbCountry.removeAllItems();
        for (CountryNetwork cn : system.getCountryNetworkList()) {
            cmbCountry.addItem(cn);

        }
    }

    private void populateStateComboBox(CountryNetwork cn) {
        cmbState.removeAllItems();
        for (StateNetwork sn : cn.getStateNetwork()) {
            cmbState.addItem(sn);
        }
    }

    private void populateCityComboBox(StateNetwork sn) {
        cmbCity.removeAllItems();
        for (CityNetwork cin : sn.getCityNetwork()) {

            cmbCity.addItem(cin);
        }
    }

    private void populatePharmacyEnterpriseComboBox(CityNetwork cin) {
        cmbPharmacy.removeAllItems();
        for (Enterprise e : cin.getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof PharmacyEnterprise) {
                cmbPharmacy.addItem(e);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUpdateMedicine = new javax.swing.JLabel();
        lblCountry = new javax.swing.JLabel();
        cmbCountry = new javax.swing.JComboBox();
        lblState = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        cmbState = new javax.swing.JComboBox();
        cmbCity = new javax.swing.JComboBox();
        lblMedicine = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnUpdateMedicine = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbPharmacy = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbDrugs = new javax.swing.JComboBox();
        lblDrugName = new javax.swing.JLabel();
        lblDName = new javax.swing.JLabel();

        lblUpdateMedicine.setText("Update Medicine");

        lblCountry.setText("Country");

        cmbCountry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCountryActionPerformed(evt);
            }
        });

        lblState.setText("State");

        lblCity.setText("City");

        cmbState.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStateActionPerformed(evt);
            }
        });

        cmbCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCityActionPerformed(evt);
            }
        });

        lblMedicine.setText("Message");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnUpdateMedicine.setText("Update Medicine");
        btnUpdateMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMedicineActionPerformed(evt);
            }
        });

        jLabel1.setText("Pharmacies");

        cmbPharmacy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPharmacy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPharmacyActionPerformed(evt);
            }
        });

        jLabel2.setText("Pharmacy ID");

        jLabel3.setText("Drug");

        cmbDrugs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDrugsActionPerformed(evt);
            }
        });

        lblDrugName.setText("Drug Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(lblUpdateMedicine))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCountry)
                            .addComponent(lblState)
                            .addComponent(lblCity)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(lblDrugName)
                            .addComponent(lblMedicine))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMessage)
                            .addComponent(cmbCountry, 0, 126, Short.MAX_VALUE)
                            .addComponent(cmbState, 0, 126, Short.MAX_VALUE)
                            .addComponent(cmbCity, 0, 126, Short.MAX_VALUE)
                            .addComponent(cmbPharmacy, 0, 126, Short.MAX_VALUE)
                            .addComponent(cmbDrugs, 0, 126, Short.MAX_VALUE)
                            .addComponent(lblId)
                            .addComponent(lblDName)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(btnUpdateMedicine)))
                .addGap(297, 297, 297))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblUpdateMedicine)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCountry)
                    .addComponent(cmbCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblState)
                    .addComponent(cmbState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity)
                    .addComponent(cmbCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbPharmacy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbDrugs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDrugName)
                    .addComponent(lblDName))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicine)
                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btnUpdateMedicine)
                .addGap(5, 5, 5)
                .addComponent(btnBack)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPharmacyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPharmacyActionPerformed
        // TODO add your handling code here:
        Enterprise e = (Enterprise) cmbPharmacy.getSelectedItem();
        if (e != null) {
            lblId.setText(String.valueOf(e.getOrgId()));

            PharmacyEnterprise pe = (PharmacyEnterprise) e;

            ArrayList<Drug> drugList = new ArrayList<Drug>();

            for (DrugItem di : pe.getDrugItemList()) {
                boolean flag = false;
                if (di.getDrug() != null) {
                    Drug d = di.getDrug();

                    for (Drug dr : drugList) {
                        if (d == dr) {
                            flag = true;
                        }

                    }
                    if (flag == false) {
                        drugList.add(d);
                    }
                }
            }
            cmbDrugs.removeAllItems();

            for (Drug d : drugList) {
                cmbDrugs.addItem(d);
            }
        }
    }//GEN-LAST:event_cmbPharmacyActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMedicineActionPerformed
        // TODO add your handling code here:
        Enterprise e = (Enterprise) cmbPharmacy.getSelectedItem();
        if (e == null) {
            JOptionPane.showMessageDialog(null, "Select a pharmacy first");
            return;
        }
        String message = txtMessage.getText();

        if (message.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a message that you want to update.");
            return;
        }
        PharmacyWorkRequest pwr = new PharmacyWorkRequest();
        Drug d = (Drug) cmbDrugs.getSelectedItem();
        pwr.setSender(encounter.getDoctor());
        pwr.setMessage(message);
        pwr.setEnterprise(encounter.getLabTestWorkRequest().getEnterprise());
        pwr.setPatient(encounter.getPatient());
        pwr.setStatus("Sent to pharmacy");
        pwr.setPharmacyName(e.getOrgName());
        pwr.setDrug(d);
        
        boolean f = false;
        for(Drug dr : encounter.getDrugList()){
            if(dr==d){
                f= true;
            }
        }
        if(f==false){
            encounter.getDrugList().add(d);
        }

        e.getWorkQueue().getWorkRequestList().add(pwr);
        encounter.getPatient().getWorkQueue().getWorkRequestList().add(pwr);
        encounter.getDoctor().getWorkQueue().getWorkRequestList().add(pwr);
        btnUpdateMedicine.setEnabled(false);


    }//GEN-LAST:event_btnUpdateMedicineActionPerformed

    private void cmbCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCountryActionPerformed
        // TODO add your handling code here:
        CountryNetwork cn = (CountryNetwork) cmbCountry.getSelectedItem();
        if (cn != null) {
            populateStateComboBox(cn);
        }
    }//GEN-LAST:event_cmbCountryActionPerformed

    private void cmbStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStateActionPerformed
        // TODO add your handling code here:
        StateNetwork sn = (StateNetwork) cmbState.getSelectedItem();
        if (sn != null) {
            populateCityComboBox(sn);
        }
    }//GEN-LAST:event_cmbStateActionPerformed

    private void cmbCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCityActionPerformed
        // TODO add your handling code here:
        CityNetwork cin = (CityNetwork) cmbCity.getSelectedItem();
        if (cin != null) {
            populatePharmacyEnterpriseComboBox(cin);
        }
    }//GEN-LAST:event_cmbCityActionPerformed

    private void cmbDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDrugsActionPerformed
        // TODO add your handling code here:
        Drug drug = (Drug) cmbDrugs.getSelectedItem();
        if (drug != null) {
            lblDName.setText(drug.getDrugName());
        }
    }//GEN-LAST:event_cmbDrugsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdateMedicine;
    private javax.swing.JComboBox cmbCity;
    private javax.swing.JComboBox cmbCountry;
    private javax.swing.JComboBox cmbDrugs;
    private javax.swing.JComboBox cmbPharmacy;
    private javax.swing.JComboBox cmbState;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblDName;
    private javax.swing.JLabel lblDrugName;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMedicine;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblUpdateMedicine;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
