/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.EcoSystem;
import Business.Encounter.Encounter;
import Business.Enterprise.ClinicEnterprise;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Person.Doctor;
import Business.Person.Person;
import Business.WorkQueue.LabTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saurabh Goyal
 */
public class ViewLabRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewLabRequestJPanel
     */
    private JPanel userProcessContainer;
    private Doctor doctor;
    private EcoSystem system;

    public ViewLabRequestJPanel(JPanel userProcessContainer, EcoSystem system, Person person) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.doctor = (Doctor) person;
        this.system = system;
        populateEnterpriseComboBox();

    }

    private void populateEnterpriseComboBox() {
        cmbEnterprise.removeAllItems();

        for (Enterprise e : doctor.getEnterpriseList()) {
            cmbEnterprise.addItem(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLabRequests = new javax.swing.JLabel();
        cmbEnterprise = new javax.swing.JComboBox();
        lblEnterprise = new javax.swing.JLabel();
        lblEnterpriseId = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWorkRequest = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnUpdateMedicine = new javax.swing.JButton();

        lblLabRequests.setText("Lab Requests");

        cmbEnterprise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEnterpriseActionPerformed(evt);
            }
        });

        lblEnterprise.setText("Enterprise");

        lblEnterpriseId.setText("Enterprise ID");

        tblWorkRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Encounter ID", "Message", "Patient MRN", "Receiver", "Status", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblWorkRequest);
        if (tblWorkRequest.getColumnModel().getColumnCount() > 0) {
            tblWorkRequest.getColumnModel().getColumn(0).setResizable(false);
            tblWorkRequest.getColumnModel().getColumn(1).setResizable(false);
            tblWorkRequest.getColumnModel().getColumn(2).setResizable(false);
            tblWorkRequest.getColumnModel().getColumn(3).setResizable(false);
            tblWorkRequest.getColumnModel().getColumn(4).setResizable(false);
            tblWorkRequest.getColumnModel().getColumn(5).setResizable(false);
        }

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnUpdateMedicine.setText("Update Medicine");
        btnUpdateMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMedicineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnUpdateMedicine)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(276, 276, 276)
                            .addComponent(lblLabRequests))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblEnterprise)
                                .addComponent(lblEnterpriseId))
                            .addGap(72, 72, 72)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblId)
                                .addComponent(cmbEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addComponent(btnBack))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblLabRequests)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEnterprise))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterpriseId)
                    .addComponent(lblId))
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnUpdateMedicine)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEnterpriseActionPerformed
        // TODO add your handling code here:
        Enterprise e = (Enterprise) cmbEnterprise.getSelectedItem();

        if (e != null) {
            lblId.setText(String.valueOf(e.getOrgId()));

            if (e instanceof HospitalEnterprise) {

                HospitalEnterprise he = (HospitalEnterprise) e;

                DefaultTableModel dtm = (DefaultTableModel) tblWorkRequest.getModel();
                dtm.setRowCount(0);

                for (Encounter encounter : he.getEncounterList()) {
                    if (encounter.getLabTestWorkRequest() != null) {
                        if (encounter.getDoctor() == doctor) {
                            LabTestWorkRequest ltwr = encounter.getLabTestWorkRequest();
                            if ((ltwr.getPatient().getPreferredDoctor() == doctor) || (ltwr.getPatient().getTemproryDoctor() == doctor)) {

                                Object[] row = new Object[6];
                                row[0] = encounter;
                                row[1] = ltwr;
                                row[2] = ltwr.getPatient().getMedicalRecordNumber();
                                if (ltwr.getReceiver() != null) {
                                    row[3] = ltwr.getReceiver().getFirstName() + " " + ltwr.getReceiver().getLastName();
                                }
                                row[4] = ltwr.getStatus();
                                row[5] = ltwr.getLabTestResult();

                                dtm.addRow(row);
                            }
                        }
                    }
                }
            }

            if (e instanceof ClinicEnterprise) {
                ClinicEnterprise ce = (ClinicEnterprise) e;
                DefaultTableModel dtm = (DefaultTableModel) tblWorkRequest.getModel();
                dtm.setRowCount(0);

                for (Encounter encounter : ce.getEncounterList()) {

                    if (encounter.getDoctor() == doctor) {

                        if (encounter.getLabTestWorkRequest() != null) {

                            LabTestWorkRequest ltwr = encounter.getLabTestWorkRequest();
                            if ((ltwr.getPatient().getPreferredDoctor() == doctor) || (ltwr.getPatient().getTemproryDoctor() == doctor)) {

                                Object[] row = new Object[6];
                                row[0] = encounter;
                                row[1] = ltwr;
                                row[2] = ltwr.getPatient().getMedicalRecordNumber();
                                if (ltwr.getReceiver() != null) {
                                    row[3] = ltwr.getReceiver().getFirstName() + " " + ltwr.getReceiver().getLastName();
                                }
                                row[4] = ltwr.getStatus();
                                row[5] = ltwr.getLabTestResult();

                                dtm.addRow(row);
                            }

                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_cmbEnterpriseActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMedicineActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblWorkRequest.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Select a request first.");
            return;
        }
        Encounter encounter = (Encounter) tblWorkRequest.getValueAt(selectedRow, 0);

        UpdateMedicineJPanel umjp = new UpdateMedicineJPanel(userProcessContainer, system, encounter);
        userProcessContainer.add("Update Medicine", umjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnUpdateMedicineActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdateMedicine;
    private javax.swing.JComboBox cmbEnterprise;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblEnterpriseId;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblLabRequests;
    private javax.swing.JTable tblWorkRequest;
    // End of variables declaration//GEN-END:variables
}
