/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.DoctorRole;

import Business.WorkQueue.HospitalEnterpriseAdminWorkRequest;
import Business.WorkQueue.PatientWorkRequest;
import Business.WorkQueue.ReferDoctorWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Saurabh Goyal
 */
public class ViewRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewRequestJPanel
     */
    private JPanel userProcessContainer;
    private WorkRequest wr;
    public ViewRequestJPanel(JPanel userProcessContainer, WorkRequest wr) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.wr = wr;
        lblAppointmentDetails.setVisible(false);
        txtAppointmentDetails.setVisible(false);
        populateTextFields();
        
    }
    private void populateTextFields(){
        
        if(wr instanceof HospitalEnterpriseAdminWorkRequest){
            
            HospitalEnterpriseAdminWorkRequest heawr = (HospitalEnterpriseAdminWorkRequest)wr;
            
            txtMessage.setText(heawr.getMessage());
            txtEnterpriseId.setText(String.valueOf(heawr.getSenderEnterprise().getOrgId()));
            txtEnterpriseName.setText(heawr.getSenderEnterprise().getOrgName());
            txtPatientName.setText(heawr.getPatient().getFirstName() + " " + heawr.getPatient().getLastName());
        }
        
        if(wr instanceof PatientWorkRequest){
            PatientWorkRequest pwr = (PatientWorkRequest)wr;
            
            txtMessage.setText(pwr.getMessage());
            txtEnterpriseId.setText(String.valueOf(pwr.getReceiverEnterprise().getOrgId()));
            txtEnterpriseName.setText(pwr.getReceiverEnterprise().getOrgName());
            txtPatientName.setText(pwr.getPatient().getFirstName() + " " + pwr.getPatient().getLastName());
       
            lblAppointmentDetails.setVisible(true);
            txtAppointmentDetails.setVisible(true);
            txtAppointmentDetails.setText(pwr.getAppointmentDetails());
            
        }
        
        if(wr instanceof ReferDoctorWorkRequest){
            ReferDoctorWorkRequest rdwr = (ReferDoctorWorkRequest)wr;
            
            txtMessage.setText(rdwr.getMessage());
            txtEnterpriseId.setText(String.valueOf(rdwr.getSenderEnterprise().getOrgId()));
            txtEnterpriseName.setText(rdwr.getSenderEnterprise().getOrgName());
            txtPatientName.setText(rdwr.getPatient().getFirstName() + " " + rdwr.getPatient().getLastName());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMessage = new javax.swing.JTextArea();
        txtPatientName = new javax.swing.JTextField();
        lblEnterpriseName = new javax.swing.JLabel();
        txtEnterpriseName = new javax.swing.JTextField();
        lblEnterpriseID = new javax.swing.JLabel();
        txtEnterpriseId = new javax.swing.JTextField();
        lblAppointmentDetails = new javax.swing.JLabel();
        txtAppointmentDetails = new javax.swing.JTextField();

        jLabel1.setText("View Request");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblMessage.setText("Message");

        lblPatientName.setText("Patient Name");

        txtMessage.setEditable(false);
        txtMessage.setColumns(20);
        txtMessage.setRows(5);
        jScrollPane1.setViewportView(txtMessage);

        txtPatientName.setEditable(false);

        lblEnterpriseName.setText("Enterprise Name");

        txtEnterpriseName.setEditable(false);

        lblEnterpriseID.setText("Enterprise ID");

        txtEnterpriseId.setEditable(false);

        lblAppointmentDetails.setText("Appointment Details");

        txtAppointmentDetails.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMessage)
                                    .addComponent(lblPatientName))
                                .addGap(92, 92, 92)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEnterpriseName)
                                    .addComponent(lblEnterpriseID)
                                    .addComponent(lblAppointmentDetails))
                                .addGap(60, 60, 60)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtEnterpriseId, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEnterpriseName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAppointmentDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47)
                        .addComponent(lblMessage))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientName)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterpriseName)
                    .addComponent(txtEnterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterpriseID)
                    .addComponent(txtEnterpriseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAppointmentDetails)
                    .addComponent(txtAppointmentDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAppointmentDetails;
    private javax.swing.JLabel lblEnterpriseID;
    private javax.swing.JLabel lblEnterpriseName;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JTextField txtAppointmentDetails;
    private javax.swing.JTextField txtEnterpriseId;
    private javax.swing.JTextField txtEnterpriseName;
    private javax.swing.JTextArea txtMessage;
    private javax.swing.JTextField txtPatientName;
    // End of variables declaration//GEN-END:variables
}
