/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.Encounter.Encounter;
import Business.Encounter.VitalSign;
import Business.PharmaceuticalCompany.Drug;
import UserInterface.DrugRegulatoryEmployeeRole.ViewDrugDetailJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saurabh Goyal
 */
public class ViewEncounterDetailsJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewEncounterDetailsJpanel
     */
    private JPanel userProcessContainer;
    private Encounter encounter;

    public ViewEncounterDetailsJpanel(JPanel userProcessContainer, Encounter encounter) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.encounter = encounter;
        if (encounter.getLabTestWorkRequest() == null) {
            jplLabTestResult.setVisible(false);
        }
        if (encounter.getDrugList().size() == 0) {
            jplDrugs.setVisible(false);
        }
        populateDrugTable();
        populateLabArea();
        populateOtherFields();
    }
    
    private void populateOtherFields(){
        txtPatientName.setText(encounter.getPatient().getFirstName() + " " + encounter.getPatient().getLastName());
        txtMrn.setText(String.valueOf(encounter.getPatient().getMedicalRecordNumber()));
        VitalSign vs = encounter.getVitalSign();
        txtBloodPressure.setText(String.valueOf(vs.getBloodPrssure()));
        txtHeartRate.setText(String.valueOf(vs.getHeartRate()));
        txtHeight.setText(String.valueOf(vs.getHeight()));
        txtRespiratoryRate.setText(String.valueOf(vs.getRespiratoryRate()));
        txtTemprature.setText(String.valueOf(vs.getTemprature()));
        txtWeight.setText(String.valueOf(vs.getWeight()));
    }

    private void populateDrugTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblDrugs.getModel();
        dtm.setRowCount(0);

        for (Drug d : encounter.getDrugList()) {
            Object[] row = new Object[2];
            row[0] = d;
            row[1] = d.getDrugName();

            dtm.addRow(row);
        }
    }

    private void populateLabArea() {
        if (encounter.getLabTestWorkRequest() != null) {
            txtMessage.setText(encounter.getLabTestWorkRequest().getMessage());
            txtResult.setText(encounter.getLabTestWorkRequest().getLabTestResult());
            txtStatus.setText(encounter.getLabTestWorkRequest().getStatus());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        txtPatientName = new javax.swing.JTextField();
        lblMrn = new javax.swing.JLabel();
        txtMrn = new javax.swing.JTextField();
        lblVitalSign = new javax.swing.JLabel();
        lblHeight = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblTemprature = new javax.swing.JLabel();
        lblBloodPressure = new javax.swing.JLabel();
        lblRespiratoryRate = new javax.swing.JLabel();
        lblHeartRate = new javax.swing.JLabel();
        txtHeight = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        txtTemprature = new javax.swing.JTextField();
        txtBloodPressure = new javax.swing.JTextField();
        txtRespiratoryRate = new javax.swing.JTextField();
        txtHeartRate = new javax.swing.JTextField();
        jplLabTestResult = new javax.swing.JPanel();
        lblLabTestResult = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        lblResult = new javax.swing.JLabel();
        txtResult = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jplDrugs = new javax.swing.JPanel();
        lblDrugs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrugs = new javax.swing.JTable();
        btnViewDrugDetails = new javax.swing.JButton();

        jLabel1.setText("View Encounter Details");

        lblPatientName.setText("Patient Name");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblMrn.setText("MRN");

        lblVitalSign.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVitalSign.setText("Vital Sign");

        lblHeight.setText("Height");

        lblWeight.setText("Weight");

        lblTemprature.setText("Temprature (`C)");

        lblBloodPressure.setText("Blood Pressure");

        lblRespiratoryRate.setText("Respiratory Rate");

        lblHeartRate.setText("Heart Rate");

        lblLabTestResult.setText("Lab Test Result");

        lblMessage.setText("Message");

        lblResult.setText("Result");

        lblStatus.setText("Status");

        javax.swing.GroupLayout jplLabTestResultLayout = new javax.swing.GroupLayout(jplLabTestResult);
        jplLabTestResult.setLayout(jplLabTestResultLayout);
        jplLabTestResultLayout.setHorizontalGroup(
            jplLabTestResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplLabTestResultLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplLabTestResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLabTestResult)
                    .addGroup(jplLabTestResultLayout.createSequentialGroup()
                        .addComponent(lblMessage)
                        .addGap(18, 18, 18)
                        .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(lblResult)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(lblStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jplLabTestResultLayout.setVerticalGroup(
            jplLabTestResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplLabTestResultLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLabTestResult)
                .addGap(23, 23, 23)
                .addGroup(jplLabTestResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMessage)
                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResult)
                    .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        lblDrugs.setText("Drugs");

        tblDrugs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Drug ID", "Drug Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDrugs);
        if (tblDrugs.getColumnModel().getColumnCount() > 0) {
            tblDrugs.getColumnModel().getColumn(0).setResizable(false);
            tblDrugs.getColumnModel().getColumn(1).setResizable(false);
        }

        btnViewDrugDetails.setText("View Drug Detail");
        btnViewDrugDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDrugDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jplDrugsLayout = new javax.swing.GroupLayout(jplDrugs);
        jplDrugs.setLayout(jplDrugsLayout);
        jplDrugsLayout.setHorizontalGroup(
            jplDrugsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplDrugsLayout.createSequentialGroup()
                .addComponent(lblDrugs)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jplDrugsLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jplDrugsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnViewDrugDetails)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jplDrugsLayout.setVerticalGroup(
            jplDrugsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplDrugsLayout.createSequentialGroup()
                .addComponent(lblDrugs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnViewDrugDetails)
                .addGap(312, 312, 312))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVitalSign)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPatientName)
                                .addGap(63, 63, 63)
                                .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)
                                .addComponent(lblMrn)
                                .addGap(76, 76, 76)
                                .addComponent(txtMrn, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jplLabTestResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jplDrugs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lblRespiratoryRate)
                                            .addGap(56, 56, 56)
                                            .addComponent(txtRespiratoryRate, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblHeight)
                                                .addComponent(lblWeight))
                                            .addGap(104, 104, 104)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtHeight, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                                                .addComponent(txtWeight))))
                                    .addGap(49, 49, 49)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblTemprature)
                                                .addComponent(lblBloodPressure))
                                            .addGap(56, 56, 56)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtTemprature, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                                .addComponent(txtBloodPressure)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblHeartRate)
                                            .addGap(85, 85, 85)
                                            .addComponent(txtHeartRate, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))))))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientName)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMrn)
                    .addComponent(txtMrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(lblVitalSign)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHeight)
                            .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblWeight)
                            .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTemprature)
                            .addComponent(txtTemprature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBloodPressure)
                            .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRespiratoryRate)
                    .addComponent(txtRespiratoryRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHeartRate)
                    .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jplDrugs, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jplLabTestResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewDrugDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDrugDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDrugs.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a drug first.");
            return;
        }
        Drug drug = (Drug)tblDrugs.getValueAt(selectedRow, 0);
        
        ViewDrugDetailJPanel vddjp = new ViewDrugDetailJPanel(userProcessContainer, drug);
        userProcessContainer.add("View Drug Detail",vddjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewDrugDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewDrugDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jplDrugs;
    private javax.swing.JPanel jplLabTestResult;
    private javax.swing.JLabel lblBloodPressure;
    private javax.swing.JLabel lblDrugs;
    private javax.swing.JLabel lblHeartRate;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblLabTestResult;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblMrn;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblRespiratoryRate;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTemprature;
    private javax.swing.JLabel lblVitalSign;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTable tblDrugs;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtHeartRate;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtMrn;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtRespiratoryRate;
    private javax.swing.JTextField txtResult;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTemprature;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
