/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminRole.Pharmacy;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmaceuticalCompanyEnterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.Network.CityNetwork;
import Business.Network.CountryNetwork;
import Business.Network.StateNetwork;
import Business.PharmaceuticalCompany.DrugItem;
import UserInterface.DrugRegulatoryEmployeeRole.ViewDrugDetailJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saurabh Goyal
 */
public class AddDrugItemJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddDrugItemJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private EcoSystem system;
    private PharmaceuticalCompanyEnterprise pce;

    public AddDrugItemJPanel(JPanel userProcessContainer, EcoSystem system, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.enterprise = enterprise;
        populateCompanyTable();
    }

    private void populateCompanyTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblCompany.getModel();
        dtm.setRowCount(0);

        for (CountryNetwork cn : system.getCountryNetworkList()) {
            for (StateNetwork sn : cn.getStateNetwork()) {
                for (CityNetwork cin : sn.getCityNetwork()) {
                    for (Enterprise e : cin.getEnterpriseDirectory().getEnterpriseList()) {
                        if (e instanceof PharmaceuticalCompanyEnterprise) {

                            Object[] row = new Object[2];

                            row[0] = e.getOrgId();
                            row[1] = e;

                            dtm.addRow(row);
                        }
                    }
                }
            }
        }
    }

    private void populateDrugItemTable(Enterprise e) {

        DefaultTableModel dtm = (DefaultTableModel) tblDrugItem.getModel();
        dtm.setRowCount(0);
        PharmaceuticalCompanyEnterprise pce = (PharmaceuticalCompanyEnterprise) e;
        for (DrugItem di : pce.getDrugItemList()) {
            if ("Approved".equals(di.getDrug().getIsApproved())) {
                
                Object[] row = new Object[5];

                row[0] = di;
                row[1] = di.getDrug().getDrugName();
                row[2] = di.getDateOfManufacturing();
                row[3] = di.getDateOfExpiry();
                row[4] = di.getQuantity();

                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddDrugItem = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompany = new javax.swing.JTable();
        btnSelectCompany = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDrugItem = new javax.swing.JTable();
        btnViewDrugs = new javax.swing.JButton();
        btnAddDrugItem = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        spnQuantity = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();

        lblAddDrugItem.setText("Add Drug Item");

        tblCompany.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Company ID", "Company Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCompany);
        if (tblCompany.getColumnModel().getColumnCount() > 0) {
            tblCompany.getColumnModel().getColumn(0).setResizable(false);
            tblCompany.getColumnModel().getColumn(1).setResizable(false);
        }

        btnSelectCompany.setText("Select Company");
        btnSelectCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectCompanyActionPerformed(evt);
            }
        });

        tblDrugItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug ID", "Drug Name", "Manufacturing Date", "Expiration Date", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDrugItem);
        if (tblDrugItem.getColumnModel().getColumnCount() > 0) {
            tblDrugItem.getColumnModel().getColumn(0).setResizable(false);
            tblDrugItem.getColumnModel().getColumn(1).setResizable(false);
            tblDrugItem.getColumnModel().getColumn(2).setResizable(false);
            tblDrugItem.getColumnModel().getColumn(3).setResizable(false);
            tblDrugItem.getColumnModel().getColumn(4).setResizable(false);
        }

        btnViewDrugs.setText("View Drugs");
        btnViewDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDrugsActionPerformed(evt);
            }
        });

        btnAddDrugItem.setText("Add Drug Item");
        btnAddDrugItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDrugItemActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setText("Quantity");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171)
                .addComponent(btnViewDrugs)
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(lblAddDrugItem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(btnSelectCompany))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(btnAddDrugItem)))
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblAddDrugItem)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnSelectCompany)
                .addGap(46, 46, 46)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnViewDrugs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(26, 26, 26)
                        .addComponent(btnAddDrugItem)
                        .addGap(29, 29, 29)))
                .addComponent(btnBack)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectCompanyActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCompany.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a company first.");
            return;
        }

        Enterprise enterprise = (Enterprise) tblCompany.getValueAt(selectedRow, 1);
        pce = (PharmaceuticalCompanyEnterprise) enterprise;
        populateDrugItemTable(enterprise);

    }//GEN-LAST:event_btnSelectCompanyActionPerformed

    private void btnViewDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDrugsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDrugItem.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Drug Item first.");
            return;
        }
        DrugItem di = (DrugItem) tblDrugItem.getValueAt(selectedRow, 0);

        ViewDrugDetailJPanel vddjp = new ViewDrugDetailJPanel(userProcessContainer, di.getDrug());
        userProcessContainer.add("View Drug Detail", vddjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewDrugsActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddDrugItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDrugItemActionPerformed
        // TODO add your handling code here:
        int quantity = (Integer) spnQuantity.getValue();
        int selectedRow = tblDrugItem.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Drug Item first.");
            return;
        }
        DrugItem di = (DrugItem) tblDrugItem.getValueAt(selectedRow, 0);

        if (quantity < 1 || quantity > di.getQuantity()) {
            JOptionPane.showMessageDialog(null, "Quantity entered is invalid.");
            return;
        }

        DrugItem di1 = new DrugItem();

        di1.setDateOfExpiry(di.getDateOfExpiry());
        di1.setDateOfManufacturing(di.getDateOfManufacturing());
        di1.setQuantity(quantity);
        di1.setDrug(di.getDrug());

        di.setQuantity(di.getQuantity() - quantity);

        PharmacyEnterprise pe = (PharmacyEnterprise) enterprise;
        pe.getDrugItemList().add(di1);

        for (PharmacyEnterprise pe1 : pce.getPharmacyEnterpriseList()) {
            if (pe == pe1) {
                return;
            }
        }
        pce.getPharmacyEnterpriseList().add(pe);

    }//GEN-LAST:event_btnAddDrugItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDrugItem;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSelectCompany;
    private javax.swing.JButton btnViewDrugs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAddDrugItem;
    private javax.swing.JSpinner spnQuantity;
    private javax.swing.JTable tblCompany;
    private javax.swing.JTable tblDrugItem;
    // End of variables declaration//GEN-END:variables
}
