/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminRole.Pharmacy;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.PharmaceuticalCompany.DrugItem;
import UserInterface.DrugRegulatoryEmployeeRole.ViewDrugDetailJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saurabh Goyal
 */
public class ManageDrugsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDrugsJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private EcoSystem system;

    public ManageDrugsJPanel(JPanel userProcessContainer, EcoSystem system, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        populateDrugItemList();
    }

    private void populateDrugItemList() {
        DefaultTableModel dtm = (DefaultTableModel) tblDrugItem.getModel();
        dtm.setRowCount(0);

        PharmacyEnterprise pe = (PharmacyEnterprise) enterprise;

        for (DrugItem di : pe.getDrugItemList()) {

            if (di.getDrug() != null) {
                Object[] row = new Object[5];
                row[0] = di;
                row[1] = di.getDrug().getDrugName();
                row[2] = di.getQuantity();
                row[3] = di.getDateOfManufacturing();
                row[4] = di.getDateOfExpiry();

                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManageDrugs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrugItem = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnAddDrugItem = new javax.swing.JButton();
        btnRemoveDrugItem = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnViewDrug = new javax.swing.JButton();

        lblManageDrugs.setText("Manage Drugs");

        tblDrugItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Drug ID", "Drug Name", "Quantity", "Manufacturing Date", "Date of Expiry"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDrugItem);
        if (tblDrugItem.getColumnModel().getColumnCount() > 0) {
            tblDrugItem.getColumnModel().getColumn(0).setResizable(false);
            tblDrugItem.getColumnModel().getColumn(1).setResizable(false);
            tblDrugItem.getColumnModel().getColumn(2).setResizable(false);
            tblDrugItem.getColumnModel().getColumn(3).setResizable(false);
            tblDrugItem.getColumnModel().getColumn(4).setResizable(false);
        }

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnAddDrugItem.setText("Add Drug Item");
        btnAddDrugItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDrugItemActionPerformed(evt);
            }
        });

        btnRemoveDrugItem.setText("Remove Drug Item");
        btnRemoveDrugItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveDrugItemActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnViewDrug.setText("View Drug");
        btnViewDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDrugActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(249, 249, 249)
                                .addComponent(lblManageDrugs))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnRefresh)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnRemoveDrugItem)
                                    .addGap(183, 183, 183)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnViewDrug, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAddDrugItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGap(11, 11, 11)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btnBack)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblManageDrugs)
                .addGap(58, 58, 58)
                .addComponent(btnRefresh)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDrugItem)
                    .addComponent(btnRemoveDrugItem))
                .addGap(31, 31, 31)
                .addComponent(btnViewDrug)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(43, 43, 43))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddDrugItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDrugItemActionPerformed
        // TODO add your handling code here:
        AddDrugItemJPanel adijp = new AddDrugItemJPanel(userProcessContainer, system, enterprise);
        userProcessContainer.add("Add Drug Item", adijp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddDrugItemActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDrugActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDrugItem.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Drug first.");
            return;
        }
        DrugItem di = (DrugItem) tblDrugItem.getValueAt(selectedRow, 0);

        ViewDrugDetailJPanel vddjp = new ViewDrugDetailJPanel(userProcessContainer, di.getDrug());
        userProcessContainer.add("View Drug", vddjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewDrugActionPerformed

    private void btnRemoveDrugItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveDrugItemActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDrugItem.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a Drug first.");
            return;
        }
        int c = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete this drug.", "Warning", JOptionPane.YES_NO_OPTION);
        if (c == JOptionPane.YES_OPTION) {
            DrugItem di = (DrugItem) tblDrugItem.getValueAt(selectedRow, 0);
            PharmacyEnterprise pe = (PharmacyEnterprise) enterprise;
            pe.getDrugItemList().remove(di);
            populateDrugItemList();
        }
    }//GEN-LAST:event_btnRemoveDrugItemActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateDrugItemList();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDrugItem;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRemoveDrugItem;
    private javax.swing.JButton btnViewDrug;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblManageDrugs;
    private javax.swing.JTable tblDrugItem;
    // End of variables declaration//GEN-END:variables
}
