/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DrugManagementEmployeeRole;

import Business.Enterprise.PharmaceuticalCompanyEnterprise;
import Business.PharmaceuticalCompany.Drug;
import Business.PharmaceuticalCompany.DrugItem;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saurabh Goyal
 */
public class AddDrugItemJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddDrugItemJPanel
     */
    private JPanel userProcessContainer;
    private PharmaceuticalCompanyEnterprise pce;

    public AddDrugItemJPanel(JPanel userProcessContainer, PharmaceuticalCompanyEnterprise pce) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.pce = pce;
        populatedrugTable();
        dateOfExpiryDateChooser.getDateEditor().setEnabled(false);
        dateOfManufacturingDateChooser.getDateEditor().setEnabled(false);
        
    }

    private void populatedrugTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblDrugs.getModel();
        dtm.setRowCount(0);

        for (Drug d : pce.getDrugList()) {

            Object[] row = new Object[4];

            row[0] = d;
            row[1] = d.getDrugName();
            row[2] = d.getDrugStrength();
            row[3] = d.getIsApproved();

            dtm.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrugs = new javax.swing.JTable();
        lblAddDrugItem = new javax.swing.JLabel();
        dateOfManufacturingDateChooser = new com.toedter.calendar.JDateChooser();
        lblDateOfManufacturing = new javax.swing.JLabel();
        lblDateOfExpiry = new javax.swing.JLabel();
        dateOfExpiryDateChooser = new com.toedter.calendar.JDateChooser();
        lblQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnAddDrugItem = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        tblDrugs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Drug ID", "Drug Name", "Drug Strength", "Is Approved?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDrugs);

        lblAddDrugItem.setText("Add Drug Item");

        lblDateOfManufacturing.setText("Date of Manufacturing");

        lblDateOfExpiry.setText("Date of Expiry");

        lblQuantity.setText("Quantity");

        btnAddDrugItem.setText("Add Drug Item");
        btnAddDrugItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDrugItemActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(lblAddDrugItem))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDateOfManufacturing)
                                .addGap(31, 31, 31)
                                .addComponent(dateOfManufacturingDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(lblDateOfExpiry)
                                .addGap(34, 34, 34)
                                .addComponent(dateOfExpiryDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(lblQuantity)
                        .addGap(73, 73, 73)
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(btnAddDrugItem, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDateOfManufacturing)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAddDrugItem)
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(dateOfManufacturingDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dateOfExpiryDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDateOfExpiry))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQuantity)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnAddDrugItem)
                .addGap(27, 27, 27)
                .addComponent(btnBack)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddDrugItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDrugItemActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblDrugs.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a drug first.");
            return;
        }

        if (txtQuantity.getText().isEmpty()
            ||((JTextField)dateOfExpiryDateChooser.getDateEditor().getUiComponent()).getText().isEmpty()
            ||((JTextField)dateOfManufacturingDateChooser.getDateEditor().getUiComponent()).getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Field entered is incomplete.");
            return;
        }

        try {
            Drug d = (Drug) tblDrugs.getValueAt(selectedRow, 0);
            
            if(!"Approved".equals(d.getIsApproved())){
                JOptionPane.showMessageDialog(null, "Drug has not been approved yet.");
                return;
            }

            int quantity = Integer.parseInt(txtQuantity.getText());

            String DateFormat = "EEE, MMM d, yyyy";
            SimpleDateFormat sdf = new SimpleDateFormat(DateFormat);

            Date d1 = dateOfManufacturingDateChooser.getDate();
            String dateOfManufacturing = sdf.format(d1);

            Date d2 = dateOfExpiryDateChooser.getDate();
            String dateOfExpiry = sdf.format(d2);

            if(d1.after(d2)){
                JOptionPane.showMessageDialog(null, "Date of Expiry cannot be after Manufacturing date.");
                return;
            }
            DrugItem di = new DrugItem();
            di.setDateOfExpiry(dateOfExpiry);
            di.setDateOfManufacturing(dateOfManufacturing);
            di.setDrug(d);
            di.setQuantity(quantity);

            pce.getDrugItemList().add(di);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid data is entered.");
        }
    }//GEN-LAST:event_btnAddDrugItemActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDrugItem;
    private javax.swing.JButton btnBack;
    private com.toedter.calendar.JDateChooser dateOfExpiryDateChooser;
    private com.toedter.calendar.JDateChooser dateOfManufacturingDateChooser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddDrugItem;
    private javax.swing.JLabel lblDateOfExpiry;
    private javax.swing.JLabel lblDateOfManufacturing;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JTable tblDrugs;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
