/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DrugManagementEmployeeRole;

import Business.Enterprise.PharmaceuticalCompanyEnterprise;
import Business.PharmaceuticalCompany.DrugItem;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saurabh Goyal
 */
public class ManageDrugInventoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDrugInventoryJPanel
     */
    private JPanel userProcessContainer;
    private PharmaceuticalCompanyEnterprise pce;

    public ManageDrugInventoryJPanel(JPanel userProcessContainer, PharmaceuticalCompanyEnterprise pce) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.pce = pce;
        populateDrugItemTable();

    }

    private void populateDrugItemTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblDrugItem.getModel();
        dtm.setRowCount(0);

        for (DrugItem di : pce.getDrugItemList()) {

            
                
                Object[] row = new Object[4];
                row[0] = di;
                row[1] = di.getQuantity();
                row[2] = di.getDateOfManufacturing();
                row[3] = di.getDateOfExpiry();

                dtm.addRow(row);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrugItem = new javax.swing.JTable();
        lblManageDrugInventory = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        btnAddDrugItem = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnRemoveDrugItem = new javax.swing.JButton();

        tblDrugItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Drug ID", "Quantity", "Date of Manufacturing", "Date of Expiry"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDrugItem);
        if (tblDrugItem.getColumnModel().getColumnCount() > 0) {
            tblDrugItem.getColumnModel().getColumn(0).setResizable(false);
            tblDrugItem.getColumnModel().getColumn(1).setResizable(false);
            tblDrugItem.getColumnModel().getColumn(2).setResizable(false);
            tblDrugItem.getColumnModel().getColumn(3).setResizable(false);
        }

        lblManageDrugInventory.setText("Manage Drug Inventory");

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnAddDrugItem.setText("Add Drug Item");
        btnAddDrugItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDrugItemActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRemoveDrugItem.setText("Remove Drug Inventory");
        btnRemoveDrugItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveDrugItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnRefresh)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(288, 288, 288)
                            .addComponent(lblManageDrugInventory)
                            .addGap(154, 154, 154))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnRemoveDrugItem)
                            .addGap(68, 68, 68)
                            .addComponent(btnAddDrugItem)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblManageDrugInventory)
                .addGap(44, 44, 44)
                .addComponent(btnRefresh)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDrugItem)
                    .addComponent(btnRemoveDrugItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:

        populateDrugItemTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnRemoveDrugItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveDrugItemActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDrugItem.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a drug item first.");
            return;
        }

        int c = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete.", "Warning", JOptionPane.YES_NO_OPTION);
        if (c == JOptionPane.YES_OPTION) {
            DrugItem di = (DrugItem) tblDrugItem.getValueAt(selectedRow, 0);
            pce.getDrugItemList().remove(di);

            populateDrugItemTable();
        }
    }//GEN-LAST:event_btnRemoveDrugItemActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddDrugItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDrugItemActionPerformed
        // TODO add your handling code here:
        AddDrugItemJPanel adijp = new AddDrugItemJPanel(userProcessContainer, pce);
        userProcessContainer.add("Add Drug Item", adijp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddDrugItemActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDrugItem;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRemoveDrugItem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblManageDrugInventory;
    private javax.swing.JTable tblDrugItem;
    // End of variables declaration//GEN-END:variables
}
