/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DrugManagementEmployeeRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmaceuticalCompanyEnterprise;
import Business.PharmaceuticalCompany.Drug;
import Business.PharmaceuticalCompany.DrugItem;
import UserInterface.DrugRegulatoryEmployeeRole.ViewDrugDetailJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saurabh Goyal
 */
public class ManageDrugsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDrugsJPanel
     */
    private JPanel userProcessContainer;
    private PharmaceuticalCompanyEnterprise pce;
    private Enterprise mainAuthorityEnterprise;
    
    public ManageDrugsJPanel(JPanel userProcessContainer, PharmaceuticalCompanyEnterprise pce, Enterprise mainAuthorityEnterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.pce = pce;
        this.mainAuthorityEnterprise = mainAuthorityEnterprise;
        populatedrugTable();
    }
    
    private void populatedrugTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblDrugs.getModel();
        dtm.setRowCount(0);
        
        for (Drug d : pce.getDrugList()) {
            
            Object[] row = new Object[4];
            
            row[0] = d;
            row[1] = d.getDrugName();
            row[2] = d.getDrugStrength();
            row[3] = d.getIsApproved();
            
            dtm.addRow(row);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManageDrugs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrugs = new javax.swing.JTable();
        btnRefresh = new javax.swing.JButton();
        btnAddDrug = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnRemoveDrug = new javax.swing.JButton();
        btnSendApprovalRequest = new javax.swing.JButton();
        btnViewDrug = new javax.swing.JButton();

        lblManageDrugs.setText("Manage Drugs");

        tblDrugs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Drug ID", "Drug Name", "Drug Strength", "Is Approved?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDrugs);
        if (tblDrugs.getColumnModel().getColumnCount() > 0) {
            tblDrugs.getColumnModel().getColumn(0).setResizable(false);
            tblDrugs.getColumnModel().getColumn(1).setResizable(false);
            tblDrugs.getColumnModel().getColumn(2).setResizable(false);
            tblDrugs.getColumnModel().getColumn(3).setResizable(false);
        }

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnAddDrug.setText("Add Drug");
        btnAddDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDrugActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRemoveDrug.setText("Remove Drug");
        btnRemoveDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveDrugActionPerformed(evt);
            }
        });

        btnSendApprovalRequest.setText("Send Approval Request");
        btnSendApprovalRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendApprovalRequestActionPerformed(evt);
            }
        });

        btnViewDrug.setText("View Drug");
        btnViewDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDrugActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnRefresh)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(279, 279, 279)
                                .addComponent(lblManageDrugs))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnRemoveDrug)
                                        .addGap(45, 45, 45)
                                        .addComponent(btnSendApprovalRequest)
                                        .addGap(46, 46, 46)
                                        .addComponent(btnViewDrug)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAddDrug))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnBack)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblManageDrugs)
                .addGap(46, 46, 46)
                .addComponent(btnRefresh)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddDrug)
                    .addComponent(btnRemoveDrug)
                    .addComponent(btnSendApprovalRequest)
                    .addComponent(btnViewDrug))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDrugActionPerformed
        // TODO add your handling code here:
        AddDrugJPanel adjp = new AddDrugJPanel(userProcessContainer, pce);
        userProcessContainer.add("Add Drug", adjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnAddDrugActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:

        populatedrugTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnRemoveDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveDrugActionPerformed
        // TODO add your handling code here:

        int selectedRow = tblDrugs.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a drug first.");
            return;
        }
        
        int c = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete.", "Warning", JOptionPane.YES_NO_OPTION);
        if (c == JOptionPane.YES_OPTION) {
            
            Drug d = (Drug) tblDrugs.getValueAt(selectedRow, 0);
            
            for (DrugItem di : pce.getDrugItemList()) {
                if (di.getDrug() == d) {
                    pce.getDrugItemList().remove(di);
                }
            }
            pce.getDrugList().remove(d);
            
            populatedrugTable();
            
        }
    }//GEN-LAST:event_btnRemoveDrugActionPerformed

    private void btnSendApprovalRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendApprovalRequestActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDrugs.getSelectedRow();
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a drug first.");
            return;
        }
        Drug drug = (Drug) tblDrugs.getValueAt(selectedRow, 0);
        
        if (drug.getIsApproved().equals("Yes")) {
            JOptionPane.showMessageDialog(null, "Drug has already been approved.");
            return;
        }
        
        SendApprovalRequestJPanel sarjp = new SendApprovalRequestJPanel(userProcessContainer, pce, mainAuthorityEnterprise, drug);
        userProcessContainer.add("Send Approval Request", sarjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnSendApprovalRequestActionPerformed

    private void btnViewDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDrugActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDrugs.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a drug first.");
            return;
        }
        Drug d = (Drug) tblDrugs.getValueAt(selectedRow, 0);
        ViewDrugDetailJPanel vddjp = new ViewDrugDetailJPanel(userProcessContainer, d);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewDrugActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDrug;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRemoveDrug;
    private javax.swing.JButton btnSendApprovalRequest;
    private javax.swing.JButton btnViewDrug;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblManageDrugs;
    private javax.swing.JTable tblDrugs;
    // End of variables declaration//GEN-END:variables
}
