/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ResearchEmployeeRole;

import Business.Organization.Organization;
import Business.Person.Person;
import Business.WorkQueue.ResearchOrganizationWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saurabh Goyal
 */
public class ResearchEmployeeWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ResearchEmployeeWorkAreaJPanel
     */
    private Organization o;
    private Person person;

    public ResearchEmployeeWorkAreaJPanel(Organization o, Person person) {
        initComponents();
        this.o = o;
        this.person = person;
        lblResult.setVisible(false);
        txtResult.setVisible(false);
        btnProcess.setVisible(false);
        populateWorkRequestTable();
    }

    private void populateWorkRequestTable() {

        DefaultTableModel dtm = (DefaultTableModel) tblResearchWorkRequest.getModel();
        dtm.setRowCount(0);

        for (WorkRequest wr : o.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof ResearchOrganizationWorkRequest) {
                ResearchOrganizationWorkRequest rowr = (ResearchOrganizationWorkRequest) wr;

                Object[] row = new Object[6];
                row[0] = rowr;
                row[1] = rowr.getDrug().getDrugId();
                row[2] = rowr.getDrug().getDrugName();
                if (rowr.getReceiver() != null) {
                    row[3] = rowr.getReceiver().getFirstName() + " " + rowr.getReceiver().getLastName();
                }
                row[4] = rowr.getStatus();
                row[5] = rowr.getResult();

                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblResearchEmployeeWorkArea = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResearchWorkRequest = new javax.swing.JTable();
        btnAssignToMe = new javax.swing.JButton();
        btnProcessRequest = new javax.swing.JCheckBox();
        lblResult = new javax.swing.JLabel();
        txtResult = new javax.swing.JTextField();
        btnProcess = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        lblResearchEmployeeWorkArea.setText("Research Employee Work Area");

        tblResearchWorkRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Drug ID", "Drug name", "Receiver", "Status", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblResearchWorkRequest);

        btnAssignToMe.setText("Assign To Me");
        btnAssignToMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToMeActionPerformed(evt);
            }
        });

        btnProcessRequest.setText("Process Request");
        btnProcessRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessRequestActionPerformed(evt);
            }
        });

        lblResult.setText("Result");

        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(lblResearchEmployeeWorkArea))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnAssignToMe, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(lblResult)
                        .addGap(89, 89, 89)
                        .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(btnProcessRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(btnProcess)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRefresh)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblResearchEmployeeWorkArea)
                .addGap(12, 12, 12)
                .addComponent(btnRefresh)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnAssignToMe)
                .addGap(23, 23, 23)
                .addComponent(btnProcessRequest)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblResult)
                    .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnProcess)
                .addContainerGap(71, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessRequestActionPerformed
        // TODO add your handling code here:
        if (btnProcessRequest.isSelected()) {
            lblResult.setVisible(true);
            txtResult.setVisible(true);
            btnProcess.setVisible(true);
        }
        if (!btnProcessRequest.isSelected()) {
            lblResult.setVisible(false);
            txtResult.setVisible(false);
            btnProcess.setVisible(false);
        }
    }//GEN-LAST:event_btnProcessRequestActionPerformed

    private void btnAssignToMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToMeActionPerformed
        // TODO add your handling code here:
        int selecttedRow = tblResearchWorkRequest.getSelectedRow();
        if(selecttedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a request first.");
            return;
        }
        
        ResearchOrganizationWorkRequest rowr = (ResearchOrganizationWorkRequest)tblResearchWorkRequest.getValueAt(selecttedRow,0);
        if(rowr.getReceiver()!=null){
            JOptionPane.showMessageDialog(null, "This request has already been assigned.");
            return;
        }
        rowr.setStatus("Received");
        rowr.setReceiver(person);
    }//GEN-LAST:event_btnAssignToMeActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        String result = txtResult.getText();
        
        int selecttedRow = tblResearchWorkRequest.getSelectedRow();
        if(selecttedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a request first.");
            return;
        }
        
        ResearchOrganizationWorkRequest rowr = (ResearchOrganizationWorkRequest)tblResearchWorkRequest.getValueAt(selecttedRow,0);
        
        if(rowr.getReceiver()==null){
            JOptionPane.showMessageDialog(null, "Assign this work request to yourself first.");
            return;
        }
        
        if(rowr.getReceiver()!=person){
            JOptionPane.showMessageDialog(null, "This work request is not assigned to you.");
            return;
        }
        if(rowr.getStatus()=="Processed"){
            JOptionPane.showMessageDialog(null, "This request has already been processed.");
            return;
        }
        if(result.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter the result first.");
            return;
        }
        
        rowr.setResult(result);
        rowr.setStatus("Processed");
        populateWorkRequestTable();
        
        
    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateWorkRequestTable();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignToMe;
    private javax.swing.JButton btnProcess;
    private javax.swing.JCheckBox btnProcessRequest;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblResearchEmployeeWorkArea;
    private javax.swing.JLabel lblResult;
    private javax.swing.JTable tblResearchWorkRequest;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
