/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DiseaseManagementEmployeeRole;

import Business.Organization.DiseaseManagementOrganization;
import Business.Organization.Organization;
import Business.SocialForum.Disease;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Saurabh Goyal
 */
public class AddDiseaseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddDiseaseJPanel
     */
    private JPanel userProcessContainer;
    private DiseaseManagementOrganization dmo;

    public AddDiseaseJPanel(JPanel userProcessContainer, Organization o) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.dmo = (DiseaseManagementOrganization) o;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddDisease = new javax.swing.JLabel();
        lblDiseaseName = new javax.swing.JLabel();
        lblIcdCode = new javax.swing.JLabel();
        lblSymptoms = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        txtDiseaseName = new javax.swing.JTextField();
        txtIcdCode = new javax.swing.JTextField();
        txtSymptoms = new javax.swing.JTextField();
        txtDescription = new javax.swing.JTextField();
        btnAddDisease = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        lblAddDisease.setText("Add Disease");

        lblDiseaseName.setText("Disease Name");

        lblIcdCode.setText("ICD Code");

        lblSymptoms.setText("Symptoms");

        lblDescription.setText("Description");

        txtDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionActionPerformed(evt);
            }
        });

        btnAddDisease.setText("Add Disease");
        btnAddDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDiseaseActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(lblAddDisease))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDiseaseName)
                            .addComponent(lblIcdCode)
                            .addComponent(lblSymptoms)
                            .addComponent(lblDescription))
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDiseaseName)
                            .addComponent(txtIcdCode)
                            .addComponent(txtSymptoms)
                            .addComponent(txtDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(btnAddDisease, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnBack)))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblAddDisease)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiseaseName)
                    .addComponent(txtDiseaseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIcdCode)
                    .addComponent(txtIcdCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSymptoms)
                    .addComponent(txtSymptoms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescription)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnAddDisease, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriptionActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDiseaseActionPerformed
        // TODO add your handling code here:
        if (txtDescription.getText().isEmpty() || txtDiseaseName.getText().isEmpty() || txtIcdCode.getText().isEmpty()
                || txtSymptoms.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Fields are incompletely entered");
            return;
        }
        try {
            String diseaseName = txtDiseaseName.getText();
            float icdCode = Float.parseFloat(txtIcdCode.getText());
            String symptoms = txtSymptoms.getText();
            String description = txtDescription.getText();

            Disease disease = new Disease();
            disease.setDescription(description);
            disease.setDiseaseName(diseaseName);
            disease.setIcdCode(icdCode);
            disease.setSymptoms(symptoms);

            dmo.getDiseaseList().add(disease);
            txtDescription.setText(null);
            txtDiseaseName.setText(null);
            txtIcdCode.setText(null);
            txtSymptoms.setText(null);
            
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Invalid data is entered.");
        
        }
    }//GEN-LAST:event_btnAddDiseaseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDisease;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblAddDisease;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblDiseaseName;
    private javax.swing.JLabel lblIcdCode;
    private javax.swing.JLabel lblSymptoms;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtDiseaseName;
    private javax.swing.JTextField txtIcdCode;
    private javax.swing.JTextField txtSymptoms;
    // End of variables declaration//GEN-END:variables
}
