/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package UserInterface.AdminRole.PharmaceuticalCompany;

import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmaceuticalCompanyEnterprise;
import Business.Enterprise.PharmacyEnterprise;
import Business.PharmaceuticalCompany.Drug;
import Business.WorkQueue.CallBackWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saurabh Goyal
 */
public class DrugCallBackJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrugCallBackJPanel
     */
    private JPanel userProcessContainer;
    private PharmaceuticalCompanyEnterprise pharmaceuticalCompanyEnterprise;
    public DrugCallBackJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.pharmaceuticalCompanyEnterprise = (PharmaceuticalCompanyEnterprise)enterprise;
        populateDrugTable();
    }
    
    private void populateDrugTable(){
        DefaultTableModel dtm = (DefaultTableModel)tblDrugs.getModel();
        dtm.setRowCount(0);
        
        for(Drug d : pharmaceuticalCompanyEnterprise.getDrugList()){
            if(d.getIsApproved().equals("Approved")){
                Object[] row = new Object[3];
                
                row[0] = d;
                row[1] = d.getDrugName();
                row[2] = d.getIsApproved();
                
                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDrugCallBack = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrugs = new javax.swing.JTable();
        lblMessage = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        btnSendRequest = new javax.swing.JButton();

        lblDrugCallBack.setText("Drug Call Back ");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Drug");

        tblDrugs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Drug ID", "Drug Name", "Drug Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDrugs);
        if (tblDrugs.getColumnModel().getColumnCount() > 0) {
            tblDrugs.getColumnModel().getColumn(0).setResizable(false);
            tblDrugs.getColumnModel().getColumn(1).setResizable(false);
            tblDrugs.getColumnModel().getColumn(2).setResizable(false);
        }

        lblMessage.setText("Message");

        btnSendRequest.setText("Send Message");
        btnSendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(lblDrugCallBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lblMessage)
                        .addGap(59, 59, 59)
                        .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(btnSendRequest)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblDrugCallBack)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMessage)
                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendRequest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDrugs.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a drug first.");
            return;
        }
        
        String message  = txtMessage.getText();
        if(message.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter a message first.");
            return;
        }
        Drug drug = (Drug)tblDrugs.getValueAt(selectedRow,0);
        
        
        CallBackWorkRequest cbwr = new CallBackWorkRequest();
        cbwr.setMessage(message);
        cbwr.setSenderEnterprise(pharmaceuticalCompanyEnterprise);
        cbwr.setDrug(drug);
        
        drug.setIsApproved("Called Back");
        for(PharmacyEnterprise pe : pharmaceuticalCompanyEnterprise.getPharmacyEnterpriseList()){
            pe.getWorkQueue().getWorkRequestList().add(cbwr);
        }
        pharmaceuticalCompanyEnterprise.getWorkQueue().getWorkRequestList().add(cbwr);
        btnSendRequest.setEnabled(false);
    }//GEN-LAST:event_btnSendRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDrugCallBack;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTable tblDrugs;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
