/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminRole.PharmaceuticalCompany;

import Business.Enterprise.Enterprise;
import Business.Enterprise.PharmaceuticalCompanyEnterprise;
import Business.Organization.Organization;
import Business.Organization.ResearchOrganization;
import Business.Person.Person;
import Business.PharmaceuticalCompany.Drug;
import Business.WorkQueue.ResearchOrganizationWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Saurabh Goyal
 */
public class ManageResearchWorkRequest extends javax.swing.JPanel {

    /**
     * Creates new form ManageResearchWorkRequest
     */
    private JPanel userProcessContainer;
    private PharmaceuticalCompanyEnterprise pce;
    private ResearchOrganization ro;

    public ManageResearchWorkRequest(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.pce = (PharmaceuticalCompanyEnterprise) enterprise;

        for (Organization o : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (o instanceof ResearchOrganization) {
                ro = (ResearchOrganization) o;
            }
        }
        populateDrugComboBox();
        lblMessage.setVisible(false);
        txtMessage.setVisible(false);
        lblDName.setVisible(false);
        lblDrugId.setVisible(false);
        lblDrugName.setVisible(false);
        btnSendRequest.setVisible(false);
        cmbDrug.setVisible(false);

    }

    private void populateDrugComboBox() {
        cmbDrug.removeAllItems();

        for (Drug d : pce.getDrugList()) {
            cmbDrug.addItem(d);
        }
        populateResearchWorkRequestTable();
    }

    private void populateResearchWorkRequestTable() {
        DefaultTableModel dtm = (DefaultTableModel) tblResearchWorkRequest.getModel();
        dtm.setRowCount(0);

        for (WorkRequest wr : ro.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof ResearchOrganizationWorkRequest) {
                ResearchOrganizationWorkRequest rowr = (ResearchOrganizationWorkRequest) wr;

                Object[] row = new Object[6];
                row[0] = rowr;
                row[1] = rowr.getDrug().getDrugId();
                row[2] = rowr.getDrug().getDrugName();
                if (rowr.getReceiver() != null) {
                    row[3] = rowr.getReceiver().getFirstName() + " " + rowr.getReceiver().getLastName();
                }
                row[4] = rowr.getStatus();
                row[5] = rowr.getStatus();

                dtm.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblManageResearchWorkRequest = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnCreateRequest = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResearchWorkRequest = new javax.swing.JTable();
        btnSendRequest = new javax.swing.JButton();
        lblMessage = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        cmbDrug = new javax.swing.JComboBox();
        lblDrugId = new javax.swing.JLabel();
        lblDrugName = new javax.swing.JLabel();
        lblDName = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        lblManageResearchWorkRequest.setText("Manage Research Work Request");

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCreateRequest.setText("Create Request");
        btnCreateRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateRequestActionPerformed(evt);
            }
        });

        tblResearchWorkRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Message", "Drug ID", "Drug name", "Receiver", "Status", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblResearchWorkRequest);
        if (tblResearchWorkRequest.getColumnModel().getColumnCount() > 0) {
            tblResearchWorkRequest.getColumnModel().getColumn(0).setResizable(false);
            tblResearchWorkRequest.getColumnModel().getColumn(1).setResizable(false);
            tblResearchWorkRequest.getColumnModel().getColumn(2).setResizable(false);
            tblResearchWorkRequest.getColumnModel().getColumn(3).setResizable(false);
            tblResearchWorkRequest.getColumnModel().getColumn(4).setResizable(false);
            tblResearchWorkRequest.getColumnModel().getColumn(5).setResizable(false);
        }

        btnSendRequest.setText("Send Request");
        btnSendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestActionPerformed(evt);
            }
        });

        lblMessage.setText("Message");

        cmbDrug.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDrugActionPerformed(evt);
            }
        });

        lblDrugId.setText("Drug ID");

        lblDrugName.setText("Drug name");

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMessage)
                .addGap(51, 51, 51)
                .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDrugId)
                    .addComponent(lblDrugName))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDName)
                    .addComponent(cmbDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(156, 156, 156))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(lblManageResearchWorkRequest))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(btnSendRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(btnCreateRequest))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRefresh)))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblManageResearchWorkRequest)
                .addGap(24, 24, 24)
                .addComponent(btnRefresh)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnCreateRequest)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMessage)
                    .addComponent(txtMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDrug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDrugId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDrugName)
                    .addComponent(lblDName))
                .addGap(23, 23, 23)
                .addComponent(btnSendRequest)
                .addGap(55, 55, 55)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreateRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateRequestActionPerformed
        // TODO add your handling code here:
        if (btnCreateRequest.isSelected()) {
            lblMessage.setVisible(true);
            txtMessage.setVisible(true);
            lblDName.setVisible(true);
            lblDrugId.setVisible(true);
            lblDrugName.setVisible(true);
            btnSendRequest.setVisible(true);
            cmbDrug.setVisible(true);
        }

        if (!btnCreateRequest.isSelected()) {
            lblMessage.setVisible(false);
            txtMessage.setVisible(false);
            lblDName.setVisible(false);
            lblDrugId.setVisible(false);
            lblDrugName.setVisible(false);
            btnSendRequest.setVisible(false);
            cmbDrug.setVisible(false);
        }


    }//GEN-LAST:event_btnCreateRequestActionPerformed

    private void btnSendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestActionPerformed
        // TODO add your handling code here:
        String message = txtMessage.getText();
        Drug drug = (Drug) cmbDrug.getSelectedItem();

        if (message.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a message first.");
            return;
        }

        if (drug == null) {
            JOptionPane.showMessageDialog(null, "There is no drug manufactured yet.");
            return;
        }

        ResearchOrganizationWorkRequest rowr = new ResearchOrganizationWorkRequest();
        rowr.setMessage(message);
        rowr.setDrug(drug);
        rowr.setStatus("Sent to RO");

        ro.getWorkQueue().getWorkRequestList().add(rowr);
    }//GEN-LAST:event_btnSendRequestActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateResearchWorkRequestTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void cmbDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDrugActionPerformed
        // TODO add your handling code here:
        Drug d = (Drug)cmbDrug.getSelectedItem();
        if(d!=null){
            lblDName.setText(d.getDrugName());
        }
    }//GEN-LAST:event_cmbDrugActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JCheckBox btnCreateRequest;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSendRequest;
    private javax.swing.JComboBox cmbDrug;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDName;
    private javax.swing.JLabel lblDrugId;
    private javax.swing.JLabel lblDrugName;
    private javax.swing.JLabel lblManageResearchWorkRequest;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTable tblResearchWorkRequest;
    private javax.swing.JTextField txtMessage;
    // End of variables declaration//GEN-END:variables
}
